### ISSUE TITLE
ego security policy

### ISSUE THREAD

**Issue by Glenrun** [edgelesssys/ego#106]
Hi, I have two questions about security on ego:
1) since ego patched golang runtime on a specified version(like 1.16.7), and golang also has its own[ security vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-14185/Golang.html) reported. So my question is how ego reacts if there is any new critical security issue reported on the golang version ego patched?
2) did we do security audit on the source code ego introduced?

**Comment by thomasten** [comment]
Hi @Glenrun,

1. Currently, we monitor new Go releases. If they include critical security fixes, we'll update EGo quickly. (We also update to a new Go version for non-security reasons from time to time.)
2. Added code has ben reviewed by at least one other developer with security background, but there hasn't been an external audit.

**Comment by Glenrun** [comment]
Hi, @thomasten thanks for reply. Is there any plan for external audit?

**Comment by thomasten** [comment]
There are no plans yet. We might consider it when the project becomes more popular.

Out of curiosity, do you know any TEE SDK that has been audited?
