### ISSUE TITLE
openenclave/attestation/verifier.h: No such file or directory

### ISSUE THREAD

**Issue by hello2mao** [edgelesssys/ego#107]
### Issue description

```
/usr/local/go/pkg/mod/github.com/edgelesssys/ego@v0.4.0/eclient/ert.go:10:11: fatal error: openenclave/attestation/verifier.h: No such file or directory
 // #include <openenclave/attestation/verifier.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
But:
```
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation# pwd
/opt/openenclave/include/openenclave/attestation
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation# ls
attester.h  custom_claims.h  sgx  verifier.h
root@5cbffc85062d:/opt/openenclave/include/openenclave/attestation#
```

**Comment by thomasten** [comment]
Hi @hello2mao,
When using the eclient package, you must set CGO_CFLAGS and CGO_LDFLAGS like in the [remote attestation sample](https://github.com/edgelesssys/ego/tree/master/samples/remote_attestation). I just realized that this is missing in the package doc; will add this.

**Comment by hello2mao** [comment]
> Hi @hello2mao, When using the eclient package, you must set CGO_CFLAGS and CGO_LDFLAGS like in the [remote attestation sample](https://github.com/edgelesssys/ego/tree/master/samples/remote_attestation). I just realized that this is missing in the package doc; will add this.

```
CGO_CFLAGS=-I/opt/ego/include CGO_LDFLAGS=-L/opt/ego/lib go build main.go
```
Works for `github.com/edgelesssys/ego v0.2.2`
But failed for `github.com/edgelesssys/ego v0.4.0`

Errors:
```
# github.com/edgelesssys/ego/eclient
/usr/local/go/pkg/mod/github.com/edgelesssys/ego@v0.4.0/eclient/ert.go:10:11: fatal error: openenclave/attestation/verifier.h: No such file or directory
 // #include <openenclave/attestation/verifier.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by thomasten** [comment]
Thanks, I can now reproduce the error. This will be fixed with the next release. Until then, you can use v0.3.4 of the module.

**Comment by thomasten** [comment]
fixed in v0.4.1

**Comment by tabz11** [comment]
I am getting the same error in v1.4.4

**Comment by thomasten** [comment]
@tabz11 It works for me with v1.4.4. Is it one of the samples you're trying to build?
Does building the remote_attestation sample with
```
CGO_CFLAGS=-I/opt/ego/include CGO_LDFLAGS=-L/opt/ego/lib go build ra_client/client.go
```
work for you?
