### ISSUE TITLE
grpc server gets stuck under stress test

### ISSUE THREAD

**Issue by zcc35357949** [edgelesssys/ego#112]
### Issue description
CPU：Intel 5318Y
kernel: 5.12.19
os: debian 10
EGO：v0.4.0 (ecc1a705b7de8c15e1243f6ae888886647d838db)

Grpc server which starts with `ego run` will become stuck and can not deal with any requests after low stress test.
`strace` result:  
![image](https://user-images.githubusercontent.com/23046890/149699447-f08161fc-400d-4902-97f0-34356fc9c03e.png)
`htop` result:  
![image](https://user-images.githubusercontent.com/23046890/149699915-a6cfc852-dc79-475b-9523-5109733cb986.png)

I try to use numactl to bind server pid in serveral cpus, and the problem can not be reproduced any more.

### To reproduce

sample code: 
```
...

func PKCS7Padding(ciphertext []byte, blockSize int) []byte {
    padding := blockSize - len(ciphertext)%blockSize
    padtext := bytes.Repeat([]byte{byte(padding)}, padding)
    return append(ciphertext, padtext...)
}

func PKCS7UnPadding(origData []byte) []byte {
    length := len(origData)
    unpadding := int(origData[length-1])
    return origData[:(length - unpadding)]
}

func AesEncrypt(plaintext []byte, key, iv []byte) ([]byte, error) {
    block, err := aes.NewCipher(key)
    if err != nil {
        return nil, err
    }
    blockSize := block.BlockSize()
    plaintext = PKCS7Padding(plaintext, blockSize)
    blockMode := cipher.NewCBCEncrypter(block, iv)
    crypted := make([]byte, len(plaintext))
    blockMode.CryptBlocks(crypted, plaintext)
    return crypted, nil
}

func AesDecrypt(ciphertext []byte, key, iv []byte) ([]byte, error) {
    block, err := aes.NewCipher(key)
    if err != nil {
        return nil, err
    }
    blockSize := block.BlockSize()
    blockMode := cipher.NewCBCDecrypter(block, iv[:blockSize])
    origData := make([]byte, len(ciphertext))
    blockMode.CryptBlocks(origData, ciphertext)
    origData = PKCS7UnPadding(origData)
    return origData, nil
}

func testAes() {
    key, _ := hex.DecodeString("6368616e676520746869732070617373")
    plaintext := []byte("hello ming")

    c := make([]byte, aes.BlockSize+len(plaintext))
iv := c[:aes.BlockSize]

    ciphertext, err := AesEncrypt(plaintext, key, iv)
    if err != nil {
        panic(err)
    }
fmt.Println(base64.StdEncoding.EncodeToString(ciphertext))

    plaintext, err = AesDecrypt(ciphertext, key, iv)
    if err != nil {
        panic(err)
    }
    fmt.Println(string(plaintext))
}

const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	pb.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Printf("Received: %v", in.GetName())
        testAes()
	return &pb.HelloReply{Message: "Hello " + in.GetName()}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	log.Printf("server listening at %v", lis.Addr())
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```

1. Run a simple grpc server through ego. And do aes encryption in it's handler.
2. use [ghz](https://github.com/bojand/ghz) to test the server.
ghz -c 5000 -n 50000 --insecure --proto helloworld.proto --import-paths=/mnt/storage09/ego/samples/test/platform/vendor/googleapis,/mnt/storage09/ego/samples/test/platform/vendor/ --call helloworld.Greeter/SayHello -d '{"name":"xxx"}' 127.0.0.1:50051
3. repeat step 2 serveral times, the server will stuck and client becomes timeout.

**Comment by thomasten** [comment]
Thanks for reporting. I've not yet been able to reproduce this.

Just to make sure I got everything right:
* Your system has two 5318Y CPUs?
* If you bind the server pid to only one of the two CPUs, it works correctly?
* So I probably need a system with two CPUs to reproduce this?
* Or is it about the number of cores the pid is bound to? If so, how many cores do I need to reproduce this?

**Comment by zcc35357949** [comment]
> Thanks for reporting. I've not yet been able to reproduce this.
> 
> Just to make sure I got everything right:
> 
> * Your system has two 5318Y CPUs?
> * If you bind the server pid to only one of the two CPUs, it works correctly?
> * So I probably need a system with two CPUs to reproduce this?
> * Or is it about the number of cores the pid is bound to? If so, how many cores do I need to reproduce this?

1、yes, 5318Y cpu model, 2 physical cpus, 48 cores, 96 processors.
2、It works correctly when I bind to any core.

Additional, I found the problem can not be reproduced after I comment out all stdout print code in this test example even without core binding. I'm confused about the phenomenon.

**Comment by thomasten** [comment]
Can you try to replace `"env": null,` with `"env": [{ "name": "GOMAXPROCS", "value": "26" }],` in enclave.json?
If this runs stable, increase the number. If it gets stuck, decrease it.
After each change you must run `ego sign` again.
Please tell me the biggest number that will be stable. (I suspect it might be around 26, thus, I'd start with that.)

**Comment by zcc35357949** [comment]
Indeed it is, after `GOMAXPROCS` set 26 or 27, I can not reproduce.
However, it occurs when increasing to 28.

**Comment by zcc35357949** [comment]
> Can you try to replace `"env": null,` with `"env": [{ "name": "GOMAXPROCS", "value": "26" }],` in enclave.json? If this runs stable, increase the number. If it gets stuck, decrease it. After each change you must run `ego sign` again. Please tell me the biggest number that will be stable. (I suspect it might be around 26, thus, I'd start with that.)

Indeed it is, after GOMAXPROCS set 26 or 27, I can not reproduce.
However, it occurs when increasing to 28.

**Comment by Glenrun** [comment]
@thomasten I also encountered the same issue using the same test case with @zcc35357949, also without numact do the binding, in case we run into the same case, I uploaded the stack trace generated by pstack, hope it could help.

**Comment by Glenrun** [comment]
@thomasten two stack trace files as their name shows, one to egohost process, another for ego run process.
[egohost_stack.txt](https://github.com/edgelesssys/ego/files/7902271/egohost_stack.txt)
[egorun_stack.txt](https://github.com/edgelesssys/ego/files/7902272/egorun_stack.txt)

**Comment by Glenrun** [comment]
@thomasten gdb stacks for `ego run
![image](https://user-images.githubusercontent.com/10444152/150273287-f3cff1b4-6ed7-4360-95bf-6d6a7da6d343.png)
gdb stacks for `ego host`
![image](https://user-images.githubusercontent.com/10444152/150273348-8559d63a-4d01-4fd0-9e2a-296eeee76894.png)

**Comment by thomasten** [comment]
Thanks @Glenrun. How many cores does your machine have?
Does https://github.com/edgelesssys/ego/issues/112#issuecomment-1014647888 mitigate the problem on your machine, too?

**Comment by Glenrun** [comment]
I have 56 physical cores, 112 logic cores: 
lscpu
```
...
NUMA node0 CPU(s):               0-27,56-83
NUMA node1 CPU(s):               28-55,84-111
...
```

**Comment by Glenrun** [comment]
@thomasten what is the next release date?

**Comment by thomasten** [comment]
@Glenrun

> After I set it to `26`, it is not easy to hang, it is still working correctly after running 18 hours now, seems it is stable

Thanks for doing this, it's helpful.

> I filed an issue two months ago,[ ego built program does not scale well on multi-cores server ](https://github.com/edgelesssys/ego/issues/95), does this hang have something to do with the fix?

Kind of. Previously, GOMAXPROCS was limited to 2, so the problem couldn't occur.

> what is the next release date?

Maybe next week

**Comment by Glenrun** [comment]
@thomasten Nice, thanks for reply

**Comment by Glenrun** [comment]
@thomasten we are waiting for the new release, is there any update?

**Comment by zcc35357949** [comment]
> EGo v0.4.1 is out including the fix. Sorry for the delay.

EGo v0.4.1 (3a78efde2a6a4fbe26e66bfd5300486425070689)

**Comment by thomasten** [comment]
@zcc35357949 sorry to hear that. Can you archive the directory of your sample project and attach it to this issue?

**Comment by zcc35357949** [comment]
> @zcc35357949 sorry to hear that. Can you archive the directory of your sample project and attach it to this issue?

```
ghz -c 4000 -n 500000 --insecure --proto helloworld.proto --import-paths=/ego/samples/test/platform/vendor/googleapis,/ego/samples/test/platform/vendor/ --call helloworld.Greeter/SayHello -d '{"name":"abc"}' 127.0.0.1:50051
```
I run the above benchmark command in the same test machine. The problem occurs.

**Comment by thomasten** [comment]
Thanks. Does it work if you remove GOMAXPROCS from enclave.json?

**Comment by zcc35357949** [comment]
> Thanks. Does it work if you remove GOMAXPROCS from enclave.json?

After remove GOMAXPROCS, the problem occurs less often. But it still exists.

**Comment by thomasten** [comment]
ok, we'll investigate

**Comment by Glenrun** [comment]
@thomasten I also reproduce this issue on v0.4.1, attached pstack trace when it occurred.
[egohost_v041_pstack.txt](https://github.com/edgelesssys/ego/files/8087869/egohost_v041_pstack.txt)
[egorun_v041_pstack.txt](https://github.com/edgelesssys/ego/files/8087870/egorun_v041_pstack.txt)

**Comment by Glenrun** [comment]
> ok, we'll investigate

Hi, @thomasten , is there any progress?

**Comment by thomasten** [comment]
Yes, I think I found the root cause and have a fix that seems to work regardless of the GOMAXPROCS value. But this needs some more testing.

**Comment by Glenrun** [comment]
> Yes, I think I found the root cause and have a fix that seems to work regardless of the GOMAXPROCS value. But this needs some more testing.

@thomasten Thanks for update, waiting for the new release.

**Comment by thomasten** [comment]
v0.4.2 contains the fix. Please try it out.

**Comment by Glenrun** [comment]
> v0.4.2 contains the fix. Please try it out.

@thomasten currently it seems the issue was already fixed, thanks!

**Comment by thomasten** [comment]
We consider this to be fixed. Feel free to reopen if there are still problems.
