### ISSUE TITLE
EGo's modified Go compiler: where is it and can it be used separately?

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/ego#114]
### Use case

I wonder if EGo's modified Go compiler can be taken as-is and used in Gramine LibOS. I didn't browse through this repository, but found this blog post: https://blog.edgeless.systems/how-we-built-ego-c02220360503.

This blog post says:

> To solve this, we had to modify the Go compiler such that SYSCALLs are redirected to libc instead.

Is this the only change in the Go compiler? Does this work only as part of your EGo framework? What versions of the Go compiler you support, and do you plan to support several (like three latest) versions of the Go compiler?

### Describe your solution

My hope is to take your modified Go compiler, build Go apps using it, and throw the resulting app binaries inside Gramine. This way we remove the performance overhead of exception-handling of raw `syscall` instructions.

### Additional context

Go apps already work in Gramine, but because of the raw `syscall` instructions, Intel SGX hardware traps these instructions, the Linux kernel propagates these traps as SIGILL signals to the Gramine runtime, and Gramine emulates the corresponding syscall. This works, but it is slow due to the trap and SIGILL generation.

**Comment by thomasten** [comment]
Hi!

The compiler is here https://github.com/edgelesssys/ertgo

Binaries produced by this compiler also run without EGo. We also use it to build the MarbleRun premain that runs in Gramine. We didn't try to build more complicated apps and run them in Gramine, but I'd guess that it should work.

Further changes to the compiler besides syscall handling:
- The allocator reserves memory for a large bitmap whose size depends on the number of adressable bits. We reduced this from 48 to 47, assuming the enclave runs in user space adress range. This saves some 100 MB of enclave memory.
- Go gets time via some vdso function. (I don't remember the details.) We replaced this to a call to clock_gettime. Our implementation of clock_gettime in Edgeless RT/EGo uses vdso by itself to get the time without an ocall.
- We removed some rdtsc instructions.

We only support one version at a time. Currently, this is 1.16.7. We update it if there's a critical security fix and also on occasion.

**Comment by monavij** [comment]
This is great news. We have some use cases and we can experiment with ertgo

**Comment by thomasten** [comment]
When we started to support Go, Edgeless RT's POSIX compatibility was poor and we required some more modifications to the compiler. So using unmodified gccgo wasn't an option. As gccgo seemed not so popular and gets less frequently updated, we chose the default Go compiler.
