### ISSUE TITLE
Why there's no paper for ego?

### ISSUE THREAD

**Issue by ZhAnGeek** [edgelesssys/ego#116]
This is such a great product for the industry, help a lot about building confidential computing apps,

And also I think this can strongly help school level research about moving cloud computing into enclaves,

And also I would like to introduce Ego to my lab mates, but I can't find a formal paper of ego's philosophy and features..

It is a pity, will you guys write a paper soon? Looking forward to your publications.

**Comment by flxflx** [comment]
Thank you! It's great to hear that you like EGo :-) So far, we didn't have plans for a whitepaper, but I like the idea. We'll try to write one, but I can't give you an ETA at this point.

**Comment by Glenrun** [comment]
I like ego, it is better than Gramine in golang. Looking forward to the white paper or any documentation in detail.

**Comment by emrahsariboz** [comment]
I completely agree. The paper would have made this so much stronger and easy for us users to understand how the EGO works under the hood.
