### ISSUE TITLE
Enclave not authorized to run

### ISSUE THREAD

**Issue by pillowsofwind** [edgelesssys/ego#118]
Hello all,

I run helloworld sample well in sim mode, but failed when running in enclave. The error says

'[erthost] loading enclave ...
[error_driver2api sgx_enclave_common.cpp:273] Enclave not authorized to run, .e.g. provisioning enclave hosted in app without access rights to /dev/sgx_provision. You need add the user id to group sgx_prv or run the app as root.
ERROR: enclave_load_data failed (addr=0xc0f6c000, prot=0x1, err=0x6) (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxload.c:oe_sgx_load_enclave_data:695]
ERROR: oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [src/tools/erthost/erthost.cpp:main:265]
'
Have tried as root, not help.

I use ego 0.41, Ubuntu 20.04 with kernel version 5.13.0-30-generic and sgx driver 2.11.

**Comment by thomasten** [comment]
Hi,
Are you on an [FLC or non-FLC platform](https://docs.edgeless.systems/ego/#/getting-started/troubleshoot?id=hardware)?
Can you post the output of `apt list --installed | grep sgx`?

**Comment by pillowsofwind** [comment]
Yes, I have an FLC platform:

~~~
user@user-ThinkPad-P1-Gen-3:~$ cpuid |grep SGX
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   Software Guard Extensions (SGX) capability (0x12/0):
      SGX1 supported                         = true

running `apt list --installed | grep sgx` 

~~~
user@user-ThinkPad-P1-Gen-3:~$ apt list --installed | grep sgx

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

intel-sgx-dkms/xenial,now 2.11-5 amd64 [installed]

**Comment by pillowsofwind** [comment]
Yes, I have an FLC platform:

~~~
user@user-ThinkPad-P1-Gen-3:~$ cpuid |grep SGX
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   Software Guard Extensions (SGX) capability (0x12/0):
      SGX1 supported                         = true
~~~

running `apt list --installed | grep sgx` 

~~~
user@user-ThinkPad-P1-Gen-3:~$ apt list --installed | grep sgx

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

intel-sgx-dkms/xenial,now 2.11-5 amd64 [installed]
~~~

**Comment by thomasten** [comment]
As of kernel 5.11 you don't need to install a separate driver on FLC platforms. I suggest to `apt purge intel-sgx-dkms` and uninstall any other manually installed driver.

If, after a reboot, you get the same EGo error, please `apt install linux-base-sgx`.

**Comment by pillowsofwind** [comment]
Yeah, I followed your steps, unintalled the driver, and use the `linux-base-sgx`,
however, I encountered another error

~~~
user@user-ThinkPad-P1-Gen-3:~/Desktop/ego/samples/helloworld$ ego run helloworld
EGo v0.4.1 (3a78efde2a6a4fbe26e66bfd5300486425070689)
[erthost] loading enclave ...
[get_driver_type /home/sgx/jenkins/linux-ubuntuServer-release-build-trunk-215.1/build_target/PROD/label/Builder-UbuntuSrv18/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
ERROR: enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxload.c:oe_sgx_create_enclave:452]
ERROR: oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [src/tools/erthost/erthost.cpp:main:265]
ERROR: failed to open Intel SGX device
Install the SGX driver with: sudo ego install sgx-driver
You can use 'OE_SIMULATION=1 ego run ...' to run in simulation mode.
~~~

**Comment by pillowsofwind** [comment]
I have kernel version 5.13

**Comment by thomasten** [comment]
Yes, Ubuntu 20.04 with kernel 5.13 should have in-kernel SGX support. What's the output of `ls /dev/*sgx*`?

**Comment by pillowsofwind** [comment]
I get this:

~~~
user@user-ThinkPad-P1-Gen-3:~$ ls /dev/*sgx*
/dev/sgx_enclave  /dev/sgx_provision  /dev/sgx_vepc
~~~

**Comment by pillowsofwind** [comment]
I get this:

~~~
user@user-ThinkPad-P1-Gen-3:~$ ls /dev/*sgx*
/dev/sgx_enclave  /dev/sgx_provision  /dev/sgx_vepc
~~~

**Comment by thomasten** [comment]
In addition to these, there need to be /dev/sgx/enclave and /dev/sgx/provision.

Can you check if
```
$ cat /lib/udev/rules.d/60-linux-base-sgx.rules
# SGX DCAP LD_1.22:
SUBSYSTEM=="sgx",KERNEL=="sgx",MODE="0666"
SUBSYSTEM=="sgx",KERNEL=="sgx_prv",GROUP="sgx_prv",MODE="0660"
# SGX DCAP LD_1.33:
SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
SUBSYSTEM=="misc",KERNEL=="provision",GROUP="sgx_prv",MODE="0660"
# SGX Linux >= 5.11
SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
SUBSYSTEM=="misc",KERNEL=="sgx_provision",GROUP="sgx_prv",MODE="0660",SYMLINK+="sgx/provision"
```
is the same on your machine?
(/lib/udev/rules.d/60-linux-base-sgx.rules should have been installed by linux-base-sgx)

**Comment by pillowsofwind** [comment]
Yes, this is same on my machine.

But there is no `/dev/sgx/enclave` and `/dev/sgx/provision` on my machine

**Comment by pillowsofwind** [comment]
Using `apt list --installed | grep sgx` and I get

`linux-base-sgx/focal-updates,focal-updates,now 4.5ubuntu3.7 all [installed]`

**Comment by thomasten** [comment]
Can you try if `sudo udevadm trigger` will create `/dev/sgx/...`?

**Comment by pillowsofwind** [comment]
Somehow '/dev/sgx/...' appears, but...new error 

~~~
user@user-ThinkPad-P1-Gen-3:~/Desktop/ego/samples/helloworld$ ego run helloworld
EGo v0.4.1 (3a78efde2a6a4fbe26e66bfd5300486425070689)
[erthost] loading enclave ...
ERROR: enclave_load_data failed (addr=0xc0f6c000, prot=0x1, err=0x1001) (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxload.c:oe_sgx_load_enclave_data:695]
ERROR: oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [src/tools/erthost/erthost.cpp:main:265]
~~~

Seems sgx driver was found correctly, but brings the  `enclave_load_data`error

**Comment by thomasten** [comment]
Does `dmesg | grep -i sgx` shows any error?
If not already done, try rebooting the machine.

**Comment by pillowsofwind** [comment]
I get this 

~~~
user@user-ThinkPad-P1-Gen-3:~$ dmesg |grep -i sgx
[    0.438908] sgx: EPC section 0x70200000-0x75ffffff
~~~

Rebooting not help.

**Comment by thomasten** [comment]
I'm not sure what possibly could cause this error. You may try if the helloworld sample from Open Enclave works on your machine:
```
wget https://github.com/openenclave/openenclave/releases/download/v0.17.6/Ubuntu_2004_open-enclave_0.17.6_amd64.deb
sudo apt install ./Ubuntu_2004_open-enclave_0.17.6_amd64.deb
mkdir build_helloworld
cd build_helloworld
cmake /opt/openenclave/share/openenclave/samples/helloworld
make
host/helloworld_host enclave/enclave.signed
```

**Comment by thomasten** [comment]
Thanks for sharing your experience with this error in detail. Now we have confirmation that this isn't some special issue with @pillowsofwind's machine.

We haven't been aware before that the EGo snap needs additional package(s) installed. Even `linux-base-sgx` just came up during this investigation. AFAIK all it does is setting the udev rules. These are also set by some of the Intel packages, so you don't need both `linux-base-sgx` and the Intel packages.

We're going to investigate what are the minimal package/configuration requirements to run snap-based EGo.

> `ego run` should perhaps not print the `Install the SGX driver with: sudo ego install sgx-driver` message if the host has in-kernel SGX support and `/dev/sgx_enclave` and `/dev/sgx_provision` already exist but just aren't accessible or found under `/dev/sgx/`

Agreed. We haven't been aware that the device is actually opened via the symlink (https://github.com/intel/linux-sgx/blob/f607f89ab1ac648c3e62a23991befdeb93f9bf9d/psw/urts/linux/edmm_utility.cpp#L102), but thought that the symlinks are for backward compatibility.

**Comment by thomasten** [comment]
We added a section on [sgx device issues to the docs](https://docs.edgeless.systems/ego/#/getting-started/troubleshoot?id=sgx-device-issues). And the next EGo version will print the correct hints when one of the errors occurs. The description of #123 contains technical details in case anyone is interested.
