### ISSUE TITLE
Is there a tRNG(true random number) generator in this lib?

### ISSUE THREAD

**Issue by jrylost** [edgelesssys/ego#121]
### Use case
Thank you for your awesome support for confidential golang app development.
I need a random number generator to generate blockchain account's private key(Bitcoin or Ethereum) .
I found that intel C++ SDK support random number generator function. So I wonder if there is any way to do this in ego?
Look forward to your reply.

### Additional context
![image](https://user-images.githubusercontent.com/34121887/155838773-5bc90188-5a3a-49f4-a85e-d87e054cd066.png)

**Comment by thomasten** [comment]
Hi,
Just use [crypt/rand](https://pkg.go.dev/crypto/rand). Inside EGo, it uses the same random number generator as sgx_read_rand, which is RDRAND.

**Comment by jrylost** [comment]
> Hi, Just use [crypt/rand](https://pkg.go.dev/crypto/rand). Inside EGo, it uses the same random number generator as sgx_read_rand, which is RDRAND.

Thank you for your reply!
I understand that I will get tRNG through standard lib [crypt/rand](https://pkg.go.dev/crypto/rand) in go.
But I still want to make sure that whether the random number is generated inside the sgx or not? Or is there anyway for other processes/applications to get the random number?

**Comment by thomasten** [comment]
To clarify: Inside EGo, you won't get the standard tRNG implementation via crypto/rand, but it will use RDRAND inside SGX. That means that you don't need to modify your code. When running with EGo, it will automatically get randomness from inside SGX.

**Comment by jrylost** [comment]
> To clarify: Inside EGo, you won't get the standard tRNG implementation via crypto/rand, but it will use RDRAND inside SGX. That means that you don't need to modify your code. When running with EGo, it will automatically get randomness from inside SGX.

Thank you for your help and patience!
