### ISSUE TITLE
Support for trusted timers & counters

### ISSUE THREAD

**Issue by 9072997** [edgelesssys/ego#124]
#### Timers
This allows you to escrow data into the future. Ex: This is my password that I change every 90 days. In case I die, here is a program that will be able to un-seal a copy of that password in 100 days.
#### Counters
This allows you to prevent replay attacks on sealed data.

### Describe your solution
[Intel has a solution for trusted timers & counters](https://community.intel.com/legacyfs/online/drupal_files/managed/1b/a2/Intel-SGX-Platform-Services.pdf)
I would like to see functions added to the enclave package corresponding to 
 - `sgx_get_trusted_time()`
 - `sgx_create_monotonic_counter()`
 - `sgx_increment_monotonic_counter()`
 - `sgx_read_monotonic_counter()`
 - `sgx_destroy_monotonic_counter()`

I think it would also be useful to add functions to ecrypto to seal/verify data using a specific monotonic counter ID to prevent replay attacks.

**Comment by thomasten** [comment]
Hi,
These functions were removed with v2.8 of the Intel SDK. AFAIK there's currently no way to get trusted time or monotonic counters.

**Comment by 9072997** [comment]
Thanks anyway for looking in to it. I think I am going to be exploring [go-tpm](https://github.com/google/go-tpm) to see if I can do what I need with that.
