### ISSUE TITLE
An error occurs when calling another external api with https.

### ISSUE THREAD

**Issue by gyuguen** [edgelesssys/ego#125]
### Issue description
Hello. I'm trying to develop a feature using EGo.
I get an error when I try to do another external TLS communication.
The contents of the error are as follows.
```
failed get https url: Get "https://json-schema.org/draft/2020-12/schema": x509: certificate signed by un
known authority
panic: Get "https://json-schema.org/draft/2020-12/schema": x509: certificate signed by unknown authority

goroutine 1 [running]:
main.main()
        /home/gyuguen.jang/workspace/gyuguen/ego_ssl/app.go:13 +0x358
```

I put an example [here](https://github.com/gyuguen/ego_ssl)
A simple example
```go
func main() {
	res, err := http.Get("https://json-schema.org/draft/2020-12/schema")
	if err != nil {
		fmt.Println(fmt.Errorf("failed get https url: %w", err))
		panic(err)
	}
	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		fmt.Println(fmt.Errorf("failed read body: %w", err))
		panic(err)
	}
	fmt.Println(string(body))
}
```

### To reproduce

1. git clone https://github.com/gyuguen/ego_ssl.git
2. cd ego_ssl
3. ego-go build app.go
4. ego sign app
5. ego run app

### Expected behavior
It should simply output the json response value.
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/draft/2020-12/schema",
    "$vocabulary": {
    ....
    "$recursiveRef": {
            "$comment": "\"$recursiveRef\" has been replaced by \"$dynamicRef\".",
            "$ref": "meta/core#/$defs/uriReferenceString",
            "deprecated": true
        }
    }
}
```

### Additional info / screenshot
If I build with Go, it's working without any issues.
```shell
git clone https://github.com/gyuguen/ego_ssl.git
cd ego_ssl
go build app.go
./app
```
I don't know if I am missing something.
Wait for your reply. Thank you.😄

**Comment by gyuguen** [comment]
I solved it.
I referenced this.
https://github.com/edgelesssys/ego/blob/master/internal/attestation/maa.go#L56

I'll close the issue.

**Comment by thomasten** [comment]
Hi @gyuguen,
The cause is that the enclave can't use the root certificates from the host because they are untrusted. There are two solutions:
* As you already found out, you can use InsecureSkipVerify. Only do this if
  * you don't send secret data to the target server
  * and if you don't need trust in the replied data or verify the data by other means.
* Embed root certificates like shown in https://github.com/edgelesssys/ego/tree/master/samples/embedded_file

Thanks for bringing this up. We'll add this infos to our docs.

**Comment by gyuguen** [comment]
@thomasten 
Thank you. I have solved this problem exactly. 😀

**Comment by thomasten** [comment]
This is now documented at https://docs.edgeless.systems/ego/#/knowledge/tls
