### ISSUE TITLE
cgo links host libc

### ISSUE THREAD

**Issue by aep** [edgelesssys/ego#130]
OE won't  load a binary i'm trying to build with ego, because it contains R_X86_64_IRELATIV

it's a relocation caused by calling any GLIBC stdio function.
but according to https://github.com/openenclave/openenclave/issues/4469  glibc isnt even supposed to be involved in the build process.

since ego just calls cgo, cgo will call gcc which usually links the host libc.
was i supposed to use CC=musl-gcc to avoid this?

**Comment by aep** [comment]
i'm guessing its passing CFLAGS=-nostdinc -I/opt/edgelessrt/include/openenclave/3rdparty/libc/

but there's alot of documentation missing and finding each of those flags is tedious.

**Comment by thomasten** [comment]
I'm not sure in what circumstances this relocation type is emitted. But as a first step, you can ensure that you meet EGo's limitations regarding cgo. The most important is that you must link libraries statically, except libc, which must be linked dynamically. You can check with `ldd` as shown in the [cgo example](https://github.com/edgelesssys/ego/tree/master/samples/cgo). Also see [known cgo limitations](https://docs.edgeless.systems/ego/#/knowledge/limitations).

**Comment by aep** [comment]
this is confusing. what is gnulibc used for? as far as i understand all the libc functions come from an OE musl fork so they can be enclaved.

i did end up figuring out the flags from manually looking at the pkg-config files, ending up with the exact dependencies listed in the cgo example, but now the syscalls are broken. accept() returns "not supported"  i just don't understand where they are even coming from, given that it now links musl AND gnulibc.

**Comment by aep** [comment]
oh. but  where do i get libc functions from then? by linking gnulibc? that will result in the original problem of emitting R_X86_64_IRELATIV for stdout

**Comment by thomasten** [comment]
Yes, by (implicitly) linking glibc.
We haven't seen any libc function causing R_X86_64_IRELATIV to be emitted when compiled with ego-go. E.g., adding the following to the cgo example works on my machine: `fmt.Println(C.strcmp(C.CString("foo"), C.CString("bar")))`.
Can you provide a minimal example that fails?

**Comment by aep** [comment]
```C
#include <stdio.h>
#include <string.h>

int main(void)
{
    char tmp[10];
    char target[10];
    fgets(tmp, 10, stdin);
    strcpy(target, tmp);
}
```
```
gcc -o test -static test.c
readelf -r ./test       

Relocation section '.rela.plt' at offset 0x2f8 contains 24 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
0000004baf50  000000000025 R_X86_64_IRELATIV                    419730

```


note that --static is passed in by cgo. but even if you remove that, you get R_X86_64_COPY instead, which is also not supported by OE

**Comment by thomasten** [comment]
How do you add this to a Go program? The following works fine with EGo on my machine:
```go
package main

/*
#include <stdio.h>
#include <string.h>

char target[10];
char* foo(void)
{
    char tmp[10];
    fgets(tmp, 10, stdin);
    strcpy(target, tmp);
    return target;
}
*/
import "C"

import "fmt"

func main() {
	fmt.Println(C.GoString(C.foo()))
}
```

**Comment by aep** [comment]
this is actually php built as static lib and then included in LDFLAGS.
inside the cgo comment you probably won't drag in gnu libc headers.
let me try to get a better repro

**Comment by aep** [comment]
```bash
mkdir -p /tmp/repro/c
cd /tmp/repro/c/
cat > main.c <<EOF
#include <stdio.h>
#include <string.h>
static volatile char tmp[10];
static volatile char target[10];
void cmain()
{
    fgets(tmp, 10, stdin);
    strcpy(target, tmp);
}
EOF
gcc -static -c main.c -o main.o
ar ar rcs libout.a main.o
cd /tmp/repro/
cat > main.go <<EOF
package main
// #cgo LDFLAGS: ./c/libout.a
/*
void cmain();
*/
import "C"
import "fmt"
func main() {
	fmt.Println(C.cmain());
}
EOF
ego-go build
ego sign
EGo v0.4.2 (dafde90ae7a95bb0591f21225c8806b345a53b0d)
/opt/ego/bin/ego-oesign ERROR: oe_sgx_build_enclave(): result=OE_FAILURE (0x1)
2022-04-20T10:08:20+0000.972806Z [(H)ERROR] tid(0x7fb0086b0b80) | Unsupported elf relocation type 5
 (oe_result_t=OE_UNSUPPORTED_ENCLAVE_IMAGE) [/ertbuild/3rdparty/openenclave/openenclave-src/host/sgx/elf.c:_elf64_load_relocations:1920]
2022-04-20T10:08:20+0000.972816Z [(H)ERROR] tid(0x7fb0086b0b80) | :OE_UNSUPPORTED_ENCLAVE_IMAGE [/ertbuild/3rdparty/openenclave/openenclave-src/host/sgx/elf.c:elf64_load_relocations:1957]

```

**Comment by thomasten** [comment]
It works for me if I add `-fPIC` to the gcc command line. Can you verify this? Then I'd add this to the docs.

**Comment by aep** [comment]
yes. that unfortunately solves that repro. let me get a new one then

**Comment by aep** [comment]
sorry this is going to take longer. I can't find a small enough repro quickly and we're instructed to use gramine anyway.

but documenting -fPIC is useful i think. it made SOME of the problems go away.

**Comment by Glenrun** [comment]
So eventually EGo uses host glibc rather than musl libc? oh, how EGo did this, host libc is not partitioned into untrusted and trust?

**Comment by thomasten** [comment]
ego-go links dynamically against libc. When you run the resulting binary with EGo, all dynamic symbols will be resolved against EGo's internal libc.
