### ISSUE TITLE
runtime: out of memory: cannot allocate

### ISSUE THREAD

**Issue by TYTaO** [edgelesssys/ego#134]
### Issue description
When I try to load a 100m byte array, the program get this error.
```
runtime: out of memory: cannot allocate 100663296-byte block (3932160 in use)
fatal error: out of memory
```

### To reproduce
My enclave.json  is as follows:
```
{
 "exe": "*",
 "key": "private.pem",
 "debug": true,
 "heapSize": 512,
 "executableHeap": false,
 "productID": 1,
 "securityVersion": 1,
 "mounts": null,
 "env": null,
 "files": [
         {
         "source": "*",
         "target": "*"
         }
 ]
}
```
My program  is like this:
```
func main() {
	// 1000000  1M
	bytes := [100 * 1000000]byte{}
	fmt.Println(unsafe.Sizeof(bytes))
}
```

**Comment by thomasten** [comment]
Hi,

You can fix this by increasing heapSize to, e.g., 768.

The Go runtime may reserve more memory than currently used. Outside the enclave, it's just virtual memory that's not actually allocated. But inside the enclave, we need to preallocate this.

**Comment by TYTaO** [comment]
> Hi,
> 
> You can fix this by increasing heapSize to, e.g., 768.
> 
> The Go runtime may reserve more memory than currently used. Outside the enclave, it's just virtual memory that's not actually allocated. But inside the enclave, we need to preallocate this.

Thx.
