### ISSUE TITLE
Does ego support Local Attestation ?

### ISSUE THREAD

**Issue by ParkerXie** [edgelesssys/ego#139]
Does ego has aleady supported Local Attestation ? When the report from other processes on the same physical machine. In some cases,we only need verify other processes running on the same physical machine are in tee environment.

**Comment by thomasten** [comment]
No, it doesn't yet. But we can add it.

**Comment by ParkerXie** [comment]
Can you  help we to add this function?  or tell we how to do it ,thanks a lot.  In our scene，we deliver our program "A" that run with ego to Untrusted machine, and program "A"  need pass secret data to another program "B"  also run with ego on the same untrusted machine. the only program "A"  to identify program "B"  is "B" 's  "MRENCLAVE". If we use remote Attestation,the  Untrusted machine may use a fake PCCS.

**Comment by thomasten** [comment]
I'll take a look and then get back to you.

**Comment by thomasten** [comment]
We'll probably add this feature soon. I'll keep you informed.

**Comment by thomasten** [comment]
This has been implemented and will be included in the next release.

**Comment by ParkerXie** [comment]
@thomasten Thank you very much.

**Comment by thomasten** [comment]
Added in v1.0.0. See the local_attestation sample.
