### ISSUE TITLE
AskForHelp: cannot sign and run on different servers

### ISSUE THREAD

**Issue by Laisky** [edgelesssys/ego#140]
### Issue description

I have two servers with same OS and same hardware.

An application signed by one machine cannot be run on another machine.

### To reproduce

use `ego/samples/remote_attestation`

Steps:

1. run `ego-go build server.go` and `ego sign server` on Host-A
2. scp signed executable binary to Host-B
3. `ego run server` on Host-B

got:

```sh
Host-B# ego run server
EGo v0.5.0 (19fe24700941af32c196bce44ded7afc3e54f87f)
[erthost] loading enclave ...
ERROR: enclave_initialize failed (err=0x1001) (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxload.c:oe_sgx_initialize_enclave:743]
ERROR: oe_create_enclave failed. (Set OE_SIMULATION=1 for simulation mode.) [src/tools/erthost/erthost.cpp:main:265]
ERROR: failed to initialize the enclave
```

this application can runs on Host-A without any problem:

```sh
Host-A:ego run server
EGo v0.5.0 (948515ec2c7f32b761247c84c51c753ed1a4afa0)
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
```

BTW:

1. Host-B can run application built and signed by itself.
2. Host-B re-sign the signed by Host-A application with `ego sign server`, then it works fine

**Comment by thomasten** [comment]
Hi,
I see that you run different builds on the hosts. The file /opt/ego/share/ego-enclave will be included in the measurement. So at least this file must be identical.

**Comment by thomasten** [comment]
We're working on a solution to deploy an EGo app without requiring an EGo installation to avoid such issues.

**Comment by Laisky** [comment]
> The file /opt/ego/share/ego-enclave will be included in the measurement. So at least this file must be identical.

Thank you so much, you save my day!

> We're working on a solution to deploy an EGo app without requiring an EGo installation to avoid such issues.

I have implemented cross-machine compilation and deployment via docker, I noticed that your dockerfile is quite old, the driver and ego version are not updated, can I create a PR to change it?

**Comment by thomasten** [comment]
We've released the new version. You're welcome to suggest improvements with a PR.

**Comment by thomasten** [comment]
In v1.0.0 there's now also the `ego bundle` command to bundle your app with the EGo runtime to avoid version mismatches.
