### ISSUE TITLE
Dockerfile parse error: ARG requires exactly one argument

### ISSUE THREAD

**Issue by mHassan11** [edgelesssys/ego#141]
Hey, 
I am trying to setup docker image and faced issue when I run the build commands for docker images. My system information is 
```
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 5.13.9.rsk.1-amd64
      Architecture: x86-64
```
Docker version is as follows
```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Built:             Sat Jan 30 03:17:11 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Built:            Sat Jan 30 03:15:40 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
 runc:
  Version:          1.0.0-rc92
 docker-init:
  Version:          0.18.0
```

When I run any of the following commands inside _dockerfiles_ folder
`DOCKER_BUILDKIT=1 docker build -o. - < Dockerfile.build`
OR
`DOCKER_BUILDKIT=1 docker build --build-arg egotag=master --build-arg erttag=master -o. - < Dockerfile.build`
I encounter following error.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/48985928/173615815-c09ab963-a942-4e85-863a-4c3c5410b5df.png">

This is what line 16 of Dockerfile.build looks like.
<img width="304" alt="image" src="https://user-images.githubusercontent.com/48985928/173616442-eb86151c-db80-47a8-bf59-a115cf90df05.png">

Anyone recommended fix?

**Comment by thomasten** [comment]
Hi,
I'm on Docker version 20.10.12 and it works. But the [docs](https://docs.docker.com/engine/reference/builder/#arg) don't mention specifying two ARGs in one line, so I consider this a bug in the Dockerfile.

Can you try changing that line into two
```
ARG erttag=v0.3.2
ARG egotag=v0.5.0
```
and see if it builds?

**Comment by mHassan11** [comment]
> We're releasing a new version of EGo soon (tomorrow if all goes well) with an updated Dockerfile that should fix this. I'll ping you in this issue when it's out.

@thomasten Thank you. Appreciate your assistance and excited for getting hands on experience with the product tomorrow :)

**Comment by thomasten** [comment]
@mHassan11 The new version is there. Please try whether this works for you now.

**Comment by thomasten** [comment]
No, this step should just download the Go compiler and clone the repos. This should be fast, depending on your internet connection. Maybe there's some connectivity issue regarding that server? You may try to `wget https://golang.org/dl/go1.18.1.linux-amd64.tar.gz` on your host to find out.

**Comment by thomasten** [comment]
Did it eventually work?

**Comment by thomasten** [comment]
This is because this docker image doesn't have an [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint). We use it only for building the deb package.

**Comment by mHassan11** [comment]
> This is because this docker image doesn't have an [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint). We use it only for building the deb package.

Is there a way I can run EGo after building the docker image? I am hoping to run vault and test remote attestation with EGo.

**Comment by thomasten** [comment]
After you've built the deb package with docker, you can build the ego-dev docker image as described here https://github.com/edgelesssys/ego#build-via-docker
You can also use the prebuilt image we provide by running `docker run -it ghcr.io/edgelesssys/ego-dev`
