### ISSUE TITLE
Capture time duration

### ISSUE THREAD

**Issue by pillowsofwind** [edgelesssys/ego#156]
### Use case
Hi all! Calculate time durations for operations both inside an enclave & across an enclave are very important for performance analysis. I have two aspects of time duration to capture:

- I:How to capture time inside an enclave?
- II:How to capture time elapse from outside to inside of an enclave?

### Describe your solution
For request I, seems there is no function like `sgx_get_trusted_time()` available now, it's a bit tricky to deal with.

For request II, it seems hard to timestamp the moment call into the enclave (before `ECALL`s), since the programming model does not divide an app into untrusted/trusted parts. More importantly, it seems there is noway to achieve II unless I is solved.

**Comment by pillowsofwind** [comment]
II: I want to calculate the time elapse of a https request, from outside( reach the untrusted server ) into the enclave.

**Comment by thomasten** [comment]
II: Right, that's not easily doable with the EGo architecture.

**Comment by pillowsofwind** [comment]
I have a vague idea, since I want to collect the timestamp when ecall happens, In the doc it said
> an ECALL is performed when the enclave creates a new thread. 
It is possible to modify and recompile the ego-go compiler to locate certain ecalls?

**Comment by thomasten** [comment]
It's actually the return from an ocall that you may want to measure. EGo builds upon liboehostsock from Open Enclave with these ocalls: https://github.com/openenclave/openenclave/blob/v0.18.1/include/openenclave/edl/socket.edl
You'd need to extend the [Open Enclave patch in Edgeless RT](https://github.com/edgelesssys/edgelessrt/tree/master/3rdparty/openenclave) for this. It's a bit complicated.

**Comment by pillowsofwind** [comment]
Thanks!
