### ISSUE TITLE
Attested tls fails. 

### ISSUE THREAD

**Issue by emrahsariboz** [edgelesssys/ego#160]
### Issue description
Attestes TLS is failing

I use azure VM to run attested tls example. However, I receive following error when I run client code.

`./client -s `ego signerid public.pem
`
**on server side**

Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retrieve environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'

listening ...

2022/08/06 22:37:55 http: TLS handshake error from 127.0.0.1:47224: remote error: tls: bad certificate

**on client side**

EGo v1.0.0 (f1255317ec583ed72947f65d83881a0e46ad1ed8)
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retrieve environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
panic: Get "https://localhost:8080/secret?s=mySecret": invalid security version

goroutine 1 [running]:
main.httpGet(0xc000018300, {0xc00001c270, 0x28})
	/home/azureuser/test/ra_client/client.go:65 +0x205
main.main()
	/home/azureuser/test/ra_client/client.go:39 +0x1b6

**Comment by thomasten** [comment]
Hi,
The client expects a security version of at least 2:
https://github.com/edgelesssys/ego/blob/ee40727c0be679d884afde8ce7745147c9adc565/samples/attested_tls/ra_client/client.go#L46-L47
The server's security version is set in enclave.json:
https://github.com/edgelesssys/ego/blob/ee40727c0be679d884afde8ce7745147c9adc565/samples/attested_tls/enclave.json#L7
Maybe you haven't used this file for signing the server, but created a new one?
