### ISSUE TITLE
report.Data always has 64 bytes in localReport 

### ISSUE THREAD

**Issue by ParkerXie** [edgelesssys/ego#161]
When using enclave.GetLocalReport to generate a localreport, if the value of the reportData parameter is less than 64 bytes, using enclave.VerifyLocalReport() to  get report, the report.Data will be automatically completed to 64 bytes.
The following code will show this, when we use [49 50] as input parameter "reportData", report.Data will return [49 50 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]         
```go
package main

import (
        "fmt"

        "github.com/edgelesssys/ego/enclave"
)

func main() {
        verifyReport, _ := enclave.GetLocalReport(nil, nil)
        inBytes := []byte{49, 50}
        localReport, _ := enclave.GetLocalReport(inBytes, verifyReport)
        report, _ := enclave.VerifyLocalReport(localReport)
        fmt.Printf("reportData: %v", report.Data)
}

**Comment by thomasten** [comment]
Yes, the data is padded with zero bytes when the report is created and the length is not included in the report. This is missing in the API docs. I'll add it.
The verifier must know the length and slice it to the real length like
https://github.com/edgelesssys/ego/blob/ee40727c0be679d884afde8ce7745147c9adc565/samples/local_attestation/server/main.go#L118
