### ISSUE TITLE
Encrypt/seal data and read back from a different SGX instance 

### ISSUE THREAD

**Issue by rockhouse** [edgelesssys/ego#166]
I want two different computers with their SGXs to read the same encrypted/sealed data without providing external secrets. 
When I encrypt/seal data with the command `SealWithProductKey` on one SGX the other SGX cannot decrypt it although I am providing the same signer key as well as product ID to the program. Also tried to use the `bundle` function to create the executable for both machines. An error message I get is ```OE_INVALID_CPUSVN``` as well as ```cipher: message authentication failed``` (I need to mention I pass `nil` for `additionalData` at the moment so should not be an issue, I think the invalid CPUSVN is the real culprit). 

So question is: Is it possible to achieve what I want or are all keys somehow always bound to the CPU instance SGX is running on?
I thought it should be possible based on what is stated here https://github.com/edgelesssys/ego/blob/e1e48c9dbfdfd3cb2f2fda7602729162c9f762cc/enclave/ert.go#L205
 
My assumptions are that the key that is generated during the call of `ego build` when none is present is the “signer key”. Value `productID` is for both instances just `1`

Also not sure what `keyInfo` means and how that is important to keep for later versions? 
https://github.com/edgelesssys/ego/blob/e1e48c9dbfdfd3cb2f2fda7602729162c9f762cc/enclave/ert.go#L207

Appreciate your help.

**Comment by thomasten** [comment]
Yes, sealed data can only be decrypted on the same CPU. (As stated in the [ecrypto package docs](https://pkg.go.dev/github.com/edgelesssys/ego/ecrypto#hdr-Sealing), but we should point it out clearer.)

keyInfo should be treated as opaque data. It should be kept along with the encrypted data, but doesn't need to be protected.
For example, it contains the CPUSVN that was used when the data was sealed. As the CPUSVN is one input of the key derivation, without keyInfo you couldn't derive the same key on a newer CPUSVN.

The higher level ecrypto API handles the keyInfo for you.

**Comment by rockhouse** [comment]
Thanks for the quick response. I think a quick note in the docs wouldn't hurt. :)

**Comment by mudler** [comment]
Hey - I'm bumping into this as well - according to sgx docs ( https://sgx101.gitbook.io/sgx101/sgx-bootstrap/sealing#seal-to-the-enclave-author ) it should be in theory possible to seal/unseal against the platform key.  

@thomasten are there any plans to support this in EGO? or alternatively would you consider a PR? 

thank you!

**Comment by mudler** [comment]
Replying to myself, for reference in case someone else is bumping into this: https://community.intel.com/t5/Intel-Software-Guard-Extensions/copy-sealed-data-between-different-machines/m-p/1157846/highlight/true#M2769 

It looks for having a shared key it's needed remote attestation.

**Comment by thomasten** [comment]
@mudler Yes, the unique CPU key is always involved in the key derivation. Also for MRSIGNER, which in EGo is named "product seal key".
Do you have a specific use case in mind?

**Comment by mudler** [comment]
> [@mudler](https://github.com/mudler) Yes, the unique CPU key is always involved in the key derivation. Also for MRSIGNER, which in EGo is named "product seal key". Do you have a specific use case in mind?

Thanks for the reply! It was not entirely clear by the SGX docs/ego and generally what could be found online that this is CPU-specific - from how it is worded it looks like `MRSIGNER` is just tied to the signer key, and it could work between different hosts. I couldn't find any specific reference saying that it's unique per CPU, and looked like it was a way to share encrypted payloads between TEEs, but sadly it looks like this is not possible. 

From what I could distil from https://community.intel.com/t5/Intel-Software-Guard-Extensions/copy-sealed-data-between-different-machines/m-p/1157846/highlight/true#M2769 it looks the only way around it is using remote attestation and passing by a shared key after successfully challenging the TEE environments. 

One thing is still a bit unclear from my side - I can't find a way to get the Intel API keys to setup a custom PCCS server. It seems by following the Intel links to https://ego-docs.netlify.app/ego/reference/attest#set-up-the-pccs, it is not possible to subscribe for an api key anymore? Do you have any insight? Any help is appreciated here, thanks!

**Comment by thomasten** [comment]
You already know by now that you need to establish a shared key using remote attestation, but here are some doc hints regarding sealing for completeness:
* Here's a document from Intel that mentions "a unique set of keys are generated and stored in the processor’s fuse array": https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-intel-sgx-sealing.html
* And here's the relevant part of the EGo documentation: https://pkg.go.dev/github.com/edgelesssys/ego/ecrypto#hdr-Sealing

Regarding API key, go to https://api.portal.trustedservices.intel.com/provisioning-certification (also linked from the EGo docs). There's a "Subscribe" button that should allow you to get an API key.

**Comment by mudler** [comment]
> You already know by now that you need to establish a shared key using remote attestation, but here are some doc hints regarding sealing for completeness:
> 
>     * Here's a document from Intel that mentions "a unique set of keys are generated and stored in the processor’s fuse array": https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-intel-sgx-sealing.html
> 
>     * And here's the relevant part of the EGo documentation: https://pkg.go.dev/github.com/edgelesssys/ego/ecrypto#hdr-Sealing
> 
> 
> Regarding API key, go to https://api.portal.trustedservices.intel.com/provisioning-certification (also linked from the EGo docs). There's a "Subscribe" button that should allow you to get an API key.

Thing is, when I sign-up and hit that subscribe button I get to this page:

![Image](https://github.com/user-attachments/assets/e6183882-d922-46ad-8f0a-58c39e979862)

**Comment by thomasten** [comment]
Turns out you don't need an API key anymore. However, the Intel PCCS implementation (which was deprecated with the last DCAP release btw) doesn't know about this, so you can't use it without API key. I'll see if I can fix this for our PCCS container image and update the docs.

I think you can also do remote attestation without the PCCS and directly use the Intel PCS since the last DCAP release. But I don't have much experience with that mode yet.

**Comment by thomasten** [comment]
I updated the docs and our PCCS container image to not require an API key. For reference, it now applies this patch to the Intel source code: https://github.com/edgelesssys/ego/blob/master/pccs/apikey.patch
