### ISSUE TITLE
is original SGX measurements included in attestation report that produced by EGO

### ISSUE THREAD

**Issue by xichan-ms** [edgelesssys/ego#168]
as the title, **is original SGX measurements included in attestation report that produced by EGO**?

I notice that **original SGX measurements are included in the attestation report**, see following pic, my question is that **report produced by EGO also included**?

![image](https://user-images.githubusercontent.com/26354131/189898298-4f2051cd-1a05-4e7f-a78c-d663317cd612.png)
![image](https://user-images.githubusercontent.com/26354131/189898473-e57d8767-a848-41ff-9bf4-2d00bba7e7e8.png)

If yes, **is there any tool** (online tool is better) to deserialize the measurements from the report, I find when verify the report, only use some fields, see following pic,
![image](https://user-images.githubusercontent.com/26354131/189896902-6f40087c-a96b-4b30-bde7-f29097cf2a72.png)

**Comment by thomasten** [comment]
Hi,
The UniqueID is actually the MRENCLAVE parsed from the raw report. MRENCLAVE is the measurement of the code and data in the enclave.

**Comment by xichan-ms** [comment]
Great! 
Another question, the data in original SGX attestation report are all included in the report generated by EGO?

**Comment by thomasten** [comment]
The raw report that you get from GetRemoteReport includes all of the original SGX quote. When you pass this to VerifyRemoteReport, some of its values are verified internally. The attestation.Report returned from the function contains those values that the developer has to verify.

**Comment by xichan-ms** [comment]
Great, thanks!
