### ISSUE TITLE
how to deserialize the attestation report

### ISSUE THREAD

**Issue by xichan-ms** [edgelesssys/ego#169]
now I got the attestation report produced by [code](https://github.com/edgelesssys/ego/blob/master/samples/remote_attestation/server.go#L23) in the format of byte array, **how to deserialize it in javascript**?  is there any attestation report tool or sdk in javascript?

I also want to know the **detailed data in attestation report**, not only the following data, how can I implement it?

![image](https://user-images.githubusercontent.com/26354131/190391786-ba0b0274-edde-4646-a49a-ffa14e42c39c.png)

**Comment by thomasten** [comment]
I don't know any SGX verification library for JS.

The byte array is the data of this struct:
https://github.com/openenclave/openenclave/blob/v0.18.2/include/openenclave/internal/report.h#L71
and the `report[]` field of it is this struct:
https://github.com/openenclave/openenclave/blob/v0.18.2/include/openenclave/bits/sgx/sgxtypes.h#L673
This is the full SGX quote.

If you pass the report to VerifyRemoteReport and it returns no error, you know that you also can trust the full SGX quote, i.e., also all the fields that are not included in attestation.Report.

On the other hand, if you don't use VerifyRemoteReport, you have to manually verify the quote, which is not trivial.

**Comment by xichan-ms** [comment]
@thomasten yes, I want to manually verify the quote, how can I achieve it? is there any useful docs or materials?

**Comment by thomasten** [comment]
The reference implementation for quote verification is here: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteVerification
Documentation for the quote verification library is here in chapter 3.6: https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf

**Comment by xichan-ms** [comment]
wow, thanks a lot
