### ISSUE TITLE
only support rsa key with length 3072?

### ISSUE THREAD

**Issue by xichan-ms** [edgelesssys/ego#171]
as the reproducible build https://github.com/edgelesssys/ego/tree/master/samples/reproducible_build, I noticed that if I generate rsa key signer key with length 4096 or not 3 module like the following commands, it will encounter error, is it by design? would like to know why?

```
openssl genrsa -out private.pem -3 4096
openssl genrsa -out private.pem 3072

openssl genrsa -out private.pem -3 3072 // only this one works
```

**Comment by thomasten** [comment]
Yes, these are the only parameters that SGX accepts for the sign key. It's not a limitation introduced by EGo.

**Comment by xichan-ms** [comment]
great, thanks a lot
