### ISSUE TITLE
How to test the recovery of UniqueSealKey with keyinfo?

### ISSUE THREAD

**Issue by rockhouse** [edgelesssys/ego#174]
So based on this https://github.com/edgelesssys/ego/issues/170 I get that the `keyInfo` is to be saved to be able to generate the same key even after security patches or platform upgrade. Is there a way to test this? I guess we cannot easily downgrade a security patch level but is a mainboard switch possible/enough? How can one be sure that you can recover the key? :)

**Comment by thomasten** [comment]
I don't know a straightforward way to test this, but maybe this works: One element of the CPUSVN and thus the keyInfo is the CPU microcode version. You may be able to boot with an older microcode. Look at the output of `dmesg | grep microcode`. If it contains something like "microcode updated early", you could disable the update mechanism to run with older microcode.

Regarding mainboard switch, I'm not sure about its consequences. I'd guess that on uniprocessor systems, when keeping the same CPU, this should be ok. I don't know how the seal key is actually derived on multiprocessor systems.

**Comment by rockhouse** [comment]
Thanks @thomasten I will give the microcode approach a try and if successful I will report back. Thanks for the help. Going to close the issue for now
