### ISSUE TITLE
ERROR: :OE_UNSUPPORTED when running local attestation

### ISSUE THREAD

**Issue by berserkr** [edgelesssys/ego#176]
### Issue description

Cannot run local attestation example in simulation mode.

### To reproduce

1. Get ego up and running per instructions
2. Go to samples/local_attestation, run both server and client as follows:

OE_SIMULATION=1 ego run server/server
OE_SIMULATION=1 ego run client/client

3. Profit:

ERROR: :OE_UNSUPPORTED [openenclave-src/enclave/core/sgx/report.c:sgx_create_report:131]
panic: OE_UNSUPPORTED

goroutine 1 [running]:
main.main()
        /home/blockchain/dev/src/github.com/ego/samples/local_attestation/client/main.go:36 +0x585
ERROR: :OE_UNSUPPORTED [openenclave-src/enclave/core/sgx/report.c:sgx_create_report:131]
panic: OE_UNSUPPORTED

goroutine 1 [running]:
main.main()
        /home/blockchain/dev/src/github.com/ego/samples/local_attestation/client/main.go:36 +0x585

### Expected behavior

Expected behavior would be to execute verification successfully.

**Comment by thomasten** [comment]
Thanks for bringing this up. Yes, attestation doesn't work in simulation mode. I added a note to the example.

**Comment by berserkr** [comment]
Per comments above, behavior would be as expected :)
