### ISSUE TITLE
two confidential apps on alibaba-cloud and azure respectively, can they verify each other's remote attestation report?

### ISSUE THREAD

**Issue by xichan-ms** [edgelesssys/ego#179]
as the title, two confidential apps on alibaba-cloud and azure respectively, can they verify each other's remote attestation report? thanks

**Comment by thomasten** [comment]
It depends. Currently, you can configure only one quote provider per machine. So if the enclave should both issue its own report and verify another report from an enclave running in another cloud, the quote provider must be able to provide data for both clouds.

Regarding Azure, DCs**v3** VMs can only be used with Azure DCAP client. However, DCs**v2** can also be used with a custom [PCCS](https://docs.edgeless.systems/ego/#/reference/attest). Maybe also the Alibaba PCCS can provide data for Azure v2 VMs. If not, you'd need to set up your own.

**Comment by xichan-ms** [comment]
Thanks for your reply, how do I understand "the quote provider must be able to provide data for both clouds"? or what's data? could you give me more info about it?

"If not, you'd need to set up your own.", this method can solve verify each other's remote attestation reprot if default PCCS config in your docs not working? And could you give me more info about how to set up my own quote provider?

BTW, do you know which cloud provider provides SGX enable vps? I know Alibaba Cloud and Azure do, but AWS or Google Cloud do not. Is there any other cloud provider support this type of vps? such as: Contabo, VDSina, MacLoud, does any of them support?

**Comment by thomasten** [comment]
"data" is everything needed for issuing or verifying reports, such as PCK certificates or other collaterals that depend on the CPU.

For example, the Azure DCAP client will only provide data for Azure VMs and otherwise returns "not found". Regarding the Intel default quote provider library, it can be configured to use either, e.g., Alibaba's PCCS or your own PCCS. Depending on how the Alibaba PCCS is configured, it may only work for Alibaba VMs, or it may work like your own PCCS and may also work for Azure (v2) VMs. You'd need to try it out.

> "If not, you'd need to set up your own.", this method can solve verify each other's remote attestation reprot if default PCCS config in your docs not working?

I would expect it to work. However, it probably only works for CPUs before Icelake.

> could you give me more info about how to set up my own quote provider?

You may use our PCCS Docker image for that: https://docs.edgeless.systems/ego/#/reference/attest?id=on-premises-or-other-cloud

> which cloud provider provides SGX enable vps? I know Alibaba Cloud and Azure do, but AWS or Google Cloud do not.

Yes, that's right. In addition, I know that IBM and OVH have SGX offerings, but haven't used them.

**Comment by yuguorui** [comment]
> "data" is everything needed for issuing or verifying reports, such as PCK certificates or other collaterals that depend on the CPU.
> 

From my understanding, the PCK certificates are appending to the ECDSA quote blob in current implementation (type 5, https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/6f77ba8f153e7cecd8da3cf65a0f1bb0cdc1f638/QuoteGeneration/quote_wrapper/common/inc/sgx_quote_3.h#L63), so the verifier can use the well known data (rootcacrl, pckcrl, tcbinfo, qe_identity, which you can get from Intel) to verify.

And SGX users can easily setup their own PCCS server with [Intel's reference implementation](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs) to provide the collateral to meet the requirement of the quote verification.

**Comment by yuguorui** [comment]
So the full answer to this question could be:
1. For quote generated with Intel EPID, they are inherently verifiable on different CSPs. But they're not available on Xeon, so I'm assuming they're not the point.
2. For quote generated with Intel default quote provider library (which applies to Alibaba-Cloud SGX instance and Azure DCsv2), they can be verified with the well known collateral (rootcacrl, pckcrl, tcbinfo, qe_identity) from of PCCS on any environment.
3. For quote generated with Azure DCAP client, I am not familiar with its format, so I cannot give a confident answer here.

**Comment by thomasten** [comment]
> the PCK certificates are appending to the ECDSA quote blob in current implementation (type 5, https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/6f77ba8f153e7cecd8da3cf65a0f1bb0cdc1f638/QuoteGeneration/quote_wrapper/common/inc/sgx_quote_3.h#L63), so the verifier can use the well known data (rootcacrl, pckcrl, tcbinfo, qe_identity, which you can get from Intel) to verify.

Thanks for pointing this out. I wasn't aware of this.

I just tested all possible combinations of Azure v2 and v3 machines with Azure DCAP client or my own PCCS. This has confirmed that you can *verify* reports with any quote provider.

So the answer to the initial question is: Yes, just set up as recommended by your cloud provider and it should work.

**Comment by xichan-ms** [comment]
Great, thanks a lot @thomasten @yuguorui
