### ISSUE TITLE
About sealing modes

### ISSUE THREAD

**Issue by pillowsofwind** [edgelesssys/ego#194]
Does Ego support the two sealing modes, i.e., mrsigners and mrenclave?

- mrsigners: who signed the code binary can decrypt the encrypted sealed data.
- mrenclave: only the binary itself can decrypt the encrypted sealed data.

I notice Ego supports two sealing functions, i.e., `SealWithUniqueKey` if the data should only be decryptable by the current enclave app version. `SealWithProductKey` if it should also be decryptable by future versions of the enclave app.

Does that suggest the `SealWithUniqueKey`  is the mrenclave mode? Or both of the function calls are the mrsigners mode?

Thanks!

**Comment by thomasten** [comment]
Yes, the mapping of terms (inherited from Open Enclave) is
* UniqueID: MRENCLAVE
* SignerID: MRSIGNER
* ProductID: ISVPRODID

So as the func docs state:

"[SealWithProductKey](https://pkg.go.dev/github.com/edgelesssys/ego/ecrypto#SealWithProductKey) encrypts a given plaintext with a **key derived from the signer and product id** of the enclave." -> key bound to MRSIGNER and ISVPRODID

"[SealWithUniqueKey](https://pkg.go.dev/github.com/edgelesssys/ego/ecrypto#SealWithUniqueKey) encrypts a given plaintext with a **key derived from a measurement of the enclave**. [...] Ciphertexts can't be decrypted if the **UniqueID** of the enclave changes." -> key bound to MRENCLAVE

**Comment by pillowsofwind** [comment]
Thanks for your instant response

**Comment by pillowsofwind** [comment]
Hi,

Thanks to Thomas, our work: MISO: Legacy-compatible Privacy-preserving Single Sign-on using Trusted Execution Environments has been accepted by IEEE Euro S&P 2023 (July 3-7, Delft, Netherlands). This work intensively uses EGo on supporting the implementation of the system. The published paper would be available soon!
