### ISSUE TITLE
EGo with softHsm connection error

### ISSUE THREAD

**Issue by X-roz** [edgelesssys/ego#199]
### Issue description
When I tried with Go, I can able to connect with softHsm and retrieve the keys from the slots .
But when I tried it with EGo, I got error like

**could not open PKCS#11**
   
Even though in the enclave file, I have added the "libsofthsm2.so" file as source and target details.
Still it says like could not open that libsofthsm2.so file.

I am using this package : https://github.com/ThalesIgnite/crypto11

**Comment by thomasten** [comment]
Hi, EGo doesn't support loading of dynamic libraries, see https://docs.edgeless.systems/ego/knowledge/limitations
