### ISSUE TITLE
ERROR: dcap_quoteprov: [ERROR]: [QCNL] Load JSON config error: Missing a comma or '}' after an object member. (offset 261).

### ISSUE THREAD

**Issue by jiangxu12** [edgelesssys/ego#200]
I'm learning to use SGX and ego.When I follow the step in the sample/azure_attestation to run the server,I got the error like this :

```
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
🆗 Generated Certificate.
ERROR: dcap_quoteprov: [ERROR]: [QCNL] Load JSON config error: Missing a comma or '}' after an object member. (offset 261).

[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe065
ERROR: dcap_quoteprov: [ERROR]: [QCNL] Encountered CURL error: (60) SSL peer certificate or SSH remote key was not OK 

ERROR: dcap_quoteprov: [ERROR]: [QPL] Failed to get quote config. Error code is 0xb033

ERROR: quote3_error_t=SGX_QL_ROOT_CA_UNTRUSTED
 (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:714]
ERROR: SGX Plugin _get_report(): failed to get ecdsa report. OE_PLATFORM_ERROR (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/enclave/sgx/attester.c:_get_report:324]
panic: OE_PLATFORM_ERROR

goroutine 1 [running]:
main.main()
	/home/jx/ego/samples/azure_attestation/server.go:32 +0x4d9
```
What should I do to run the server correctly?I have installed the az-dcap-client.

**Comment by thomasten** [comment]
It seems that libsgx-dcap-default-qpl is also installed. You shouldn't have both installed, so please uninstall libsgx-dcap-default-qpl and try again.

**Comment by jiangxu12** [comment]
> It seems that libsgx-dcap-default-qpl is also installed. You shouldn't have both installed, so please uninstall libsgx-dcap-default-qpl and try again.

It uninstall the libsgx-dcap-default-qpl and try again. The previous error disappeared，but I got some new errors like this:
```
root@lenovo:/home/jx/ego/samples/azure_attestation# ego run server
EGo v1.2.0 (f272b3f4430c819530e33ef5ff6c930b3dd2afa0)
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
🆗 Generated Certificate.
ERROR: dcap_quoteprov: [ERROR]: Encountered CURL error 7 in curl_easy_perform
ERROR: dcap_quoteprov: [ERROR]: error thrown, error code: 7: curl_easy_perform
ERROR: dcap_quoteprov: [ERROR]: HTTP error (404)
ERROR: dcap_quoteprov: [ERROR]: Encountered CURL error 22 in curl_easy_perform
ERROR: dcap_quoteprov: [ERROR]: error thrown, error code: 16: curl_easy_perform
[get_platform_quote_cert_data ../qe_logic.cpp:383] p_sgx_get_quote_config returned NULL for p_pck_cert_config.
ERROR: quote3_error_t=SGX_QL_NO_PLATFORM_CERT_DATA
 (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:714]
ERROR: SGX Plugin _get_report(): failed to get ecdsa report. OE_PLATFORM_ERROR (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/enclave/sgx/attester.c:_get_report:324]
panic: OE_PLATFORM_ERROR

goroutine 1 [running]:
main.main()
	/home/jx/ego/samples/azure_attestation/server.go:32 +0x4d9
```
What does this mean?

**Comment by thomasten** [comment]
If you want to use Azure Attestation and/or az-dcap-client, the server must run on an Azure VM. For attestation of other machines, see https://docs.edgeless.systems/ego/reference/attest

**Comment by jiangxu12** [comment]
> If you want to use Azure Attestation and/or az-dcap-client, the server must run on an Azure VM. For attestation of other machines, see https://docs.edgeless.systems/ego/reference/attest


I remove the az-dcap-client and install the libsgx-dcap-default-qpl to try the sample/remote_attestation again.
I follow the On-premises or other cloud part in the  https://docs.edgeless.systems/ego/reference/attest.
I set up the PCCS successfully.
When I run **curl -kv https://localhost:8081/sgx/certification/v3/rootcacrl**, I see a  200 status code like this.
* ```
  root@lenovo:/home/jx/ego/samples/remote_attestation# curl -kv https://localhost:8081/sgx/certification/v3/rootcacrl
  
  *   Trying 127.0.0.1:8081...
  *   TCP_NODELAY set
  *   Connected to localhost (127.0.0.1) port 8081 (#0)
  *   ALPN, offering h2
  *   ALPN, offering http/1.1
  *   successfully set certificate verify locations:
  *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: /etc/ssl/certs
  *   TLSv1.3 (OUT), TLS handshake, Client hello (1):
  *   TLSv1.3 (IN), TLS handshake, Server hello (2):
  *   TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
  *   TLSv1.3 (IN), TLS handshake, Certificate (11):
  *   TLSv1.3 (IN), TLS handshake, CERT verify (15):
  *   TLSv1.3 (IN), TLS handshake, Finished (20):
  *   TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
  *   TLSv1.3 (OUT), TLS handshake, Finished (20):
  *   SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
  *   ALPN, server accepted to use http/1.1
  *   Server certificate:
  *   subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
  *   start date: Mar 18 13:48:10 2023 GMT
  *   expire date: Mar 17 13:48:10 2024 GMT
  *   issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
  *   SSL certificate verify result: self signed certificate (18), continuing anyway.
  
  > GET /sgx/certification/v3/rootcacrl HTTP/1.1
  > Host: localhost:8081
  > User-Agent: curl/7.68.0
  > Accept: */*
  
  * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
  * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
  * old SSL session ID is stale, removing
  * Mark bundle as not supporting multiuse
    **< HTTP/1.1 200 OK**
    < X-Powered-By: Express
    < Request-ID: 019bf19c791c470898778eb87c394b58
    < Content-Type: application/pkix-crl; charset=utf-8
    < Content-Length: 586
    < ETag: W/"24a-lXdmj38gN2RweL6On8KEs2rk9To"
    < Date: Mon, 20 Mar 2023 08:06:31 GMT
    < Connection: keep-alive
    < Keep-Alive: timeout=5
    < 
  * Connection #0 to host localhost left intact
    308201213081c8020101300a06082a8648ce3d0403023068311a301806035504030c11496e74656c2053475820526f6f74204341311a3018060355040a0c11496e74656c20436f72706f726174696f6e3114301206035504070c0b53616e746120436c617261310b300906035504080c024341310b3009060355040613025553170d3232303431393038333131385a170d3233303431393038333131385aa02f302d300a0603551d140403020101301f0603551d2304183016801422650cd65a9d3489f383b49552bf501b392706ac300a06082a8648ce3d0403020348003045022100b7805acf592113584c45c8b0e11b2b8a9db462a215bbf8d4fd416539d7f5ab7502207ff56984c5199cf2b23d97d37b104ec0ebb5243674f41346887a6bdfbfdfeb42
  ```
But when I **ego run server** in remote_attestation ,I still got the errors:

```
root@lenovo:/home/jx/ego/samples/remote_attestation# ego run server
EGo v1.2.0 (f272b3f4430c819530e33ef5ff6c930b3dd2afa0)
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
ERROR: dcap_quoteprov: [ERROR]: [QCNL] Load JSON config error: Missing a comma or '}' after an object member. (offset 261).

[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe065
ERROR: dcap_quoteprov: [ERROR]: [QCNL] Encountered CURL error: (60) SSL peer certificate or SSH remote key was not OK 

ERROR: dcap_quoteprov: [ERROR]: [QPL] Failed to get quote config. Error code is 0xb033

ERROR: quote3_error_t=SGX_QL_ROOT_CA_UNTRUSTED
 (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:714]
ERROR: SGX Plugin _get_report(): failed to get ecdsa report. OE_PLATFORM_ERROR (oe_result_t=OE_PLATFORM_ERROR) [openenclave-src/enclave/sgx/attester.c:_get_report:324]
OE_PLATFORM_ERROR
listening ...
```
I am very confused.

**Comment by thomasten** [comment]
Please set `use_secure_cert` to `false` in `/etc/sgx_default_qcnl.conf`. (This is just for the connection between QPL and PCCS, which doesn't need to be secure. The attestation itself is not affected.)

When we've completely solved your problem, I'll improve the docs regarding this.

**Comment by jiangxu12** [comment]
> Please set `use_secure_cert` to `false` in `/etc/sgx_default_qcnl.conf`. (This is just for the connection between QPL and PCCS, which doesn't need to be secure. The attestation itself is not affected.)
> 
> When we've completely solved your problem, I'll improve the docs regarding this.

I have set **use_secure_cert** to **false** before I got this error.
I restart the pccs and try again, the problem still exists.
![image](https://user-images.githubusercontent.com/43697225/226299844-067f51de-3561-4a05-9759-73f56b611a1d.png)
![image](https://user-images.githubusercontent.com/43697225/226301365-34063a4c-7723-4b6f-9884-ca2448be1b09.png)

I set my PCCS follow https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html.

Is this related to the fact that I used to install az-dcap-client and  libsgx-dcap-default-qpl.
Now I only have libsgx-dcap-default-qpl on my computer.Will there be residual conflicts after uninstalling az-dcap-client?

**Comment by thomasten** [comment]
There's a comma missing before use_secure_cert. It must be
`,"use_secure_cert": false`

**Comment by jiangxu12** [comment]
> There's a comma missing before use_secure_cert. It must be `,"use_secure_cert": false`
Thanks for your patient reply.
I successfully run the sample, and I got the result.
```
root@lenovo:/home/jx/ego/samples/remote_attestation# ./client -s `ego signerid public.pem`
EGo v1.2.0 (f272b3f4430c819530e33ef5ff6c930b3dd2afa0)
2023-03-20T18:06:31+0800.679765Z [(H)ERROR] tid(0x7fd9a200e700) | Invalid platform TCB level: OutOfDate (cpu_svn[0] = 0x4, pce_svn = 0xb) [/ertbuild/3rdparty/openenclave/openenclave-src/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:829]
2023-03-20T18:06:31+0800.681681Z [(H)ERROR] tid(0x7fd9a200e700) | Invalid platform TCB level: OutOfDate (cpu_svn[0] = 0x4, pce_svn = 0xb) [/ertbuild/3rdparty/openenclave/openenclave-src/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:829]
Warning: TCB level is invalid: OutOfDate
TCB level of SGX platform is outdated.
We'll ignore this issue in this sample. For an app that should run in production, you must decide which of the different TCBStatus values are acceptable for you to continue.
Sent secret over attested TLS channel.
```
Is this warning message important? If I am only using it for testing and learning, can I ignore this message.

**Comment by thomasten** [comment]
I'm glad that it works for you now :)
Yes, for testing, you can ignore the message.
For production, you would need to update things like your machine's firmware/BIOS/UEFI to apply the latest security fixes from Intel.
