### ISSUE TITLE
Could not open a file when use ego. Error: open test.txt: no such file or directory

### ISSUE THREAD

**Issue by Jansper-x** [edgelesssys/ego#202]
I want to read a content from a file, and I write like this in my program.
![image](https://user-images.githubusercontent.com/43697225/228165464-90f491ef-a656-461d-9fac-99bc97cad6f9.png)
![image](https://user-images.githubusercontent.com/43697225/228165564-96c8c912-86ec-4f62-8753-d7d7eddd0ad0.png)
When I use **go run test.txt** , I could read the content. 
But when I use **ego run test**, the program could find the file.
Why is this happening?

**Comment by Nirusu** [comment]
How does your enclave.json look like? 

By default EGo is initialized with an empty in-memory filesystem. You need to explicitly either provision files into the enclave itself (`files` in enclave.json) or mount parts of the host file system (`mounts` in enclave.json) to allow EGo to access files on your host machine.

**Comment by Nirusu** [comment]
You can find an example configuration here: https://docs.edgeless.systems/ego/reference/config#environment-variables

If you want the file to be mutable, you can mount it like this (using relative paths on both sides):
```json
  "mounts": [
    {
      "source": "test.txt",
      "target": "test.txt",
      "type": "hostfs",
      "readOnly": false
    }
  ],
```

Alternatively, if you want to "burn in" the file into the enclave (= you want it to be exactly the same every time and immutable after `ego sign`), you can embed it like this:
```json
  "files": [
    {
      "source": "test.txt",
      "target": "test.txt"
    }
  ]
```

**Comment by jiangxu12** [comment]
> You can find an example configuration here: https://docs.edgeless.systems/ego/reference/config#environment-variables
> 
> If you want the file to be mutable, you can mount it like this (using relative paths):
> 
> ```json
>   "mounts": [
>     {
>       "source": "test.txt",
>       "target": "test.txt",
>       "type": "hostfs",
>       "readOnly": false
>     }
>   ]
> ```
> 
> Alternatively, if you want to "burn in" the file into the enclave (= you want it to be exactly the same every time and immutable after `ego sign`), you can embed it like this:
> 
> ```json
>   "files": [
>     {
>       "source": "test.txt",
>       "target": "test.txt"
>     }
>   ]
> ```
Thank you. It works, when I use json:
```
 "mounts":[
         {
         "source": "sample.txt",
         "target": "sample.txt",
         "type": "hostfs",
         "readOnly": false
         }
 ],

```

If I use mounts like this:
```
 "mounts":[
      {
         "source": "/home/jx/sealing",
         "target": "/home/jx/sealing",
         "type": "hostfs",
         "readOnly": false
     }
 ],

```
does this means I could use any file and create any file in the sealing directory.

When I use enclave.json like this ,I could not read the file in the sealing directory and could not create a new fiile.
```

{
 "exe": "helloworld",
 "key": "private.pem",
 "debug": true,
 "heapSize": 512,
 "executableHeap": false,
 "productID": 1,
 "securityVersion": 1,
 "mounts":[
      {
         "source": "/home/jx/sealing",
         "target": "/home/jx/sealing",
         "type": "hostfs",
         "readOnly": false
     }
 ],
 "env": null,
 "files": []
}
```
![image](https://user-images.githubusercontent.com/43697225/228210218-0eeaeadf-640a-441f-af1f-2dda80ac2264.png)


My helloworld program like this :
```
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"

)

func main() {

    inputFile, err := os.Open("sample.txt")
    if err != nil {
        fmt.Println("无法打开文件:", err)
        return
    }
    defer inputFile.Close()


    outputFile, err := os.Create("result.txt")
    if err != nil {
        fmt.Println("无法创建文件:", err)
        return
    }
    defer outputFile.Close()

    reader := bufio.NewReader(inputFile)
    
    for {
        line, err := reader.ReadString('\n')
	if err != nil {
        	if err == io.EOF {
            		break
        	}
        	fmt.Println("读取文件时出错:", err)
    		return
    	}
	fmt.Println(line)

	_, err = outputFile.WriteString(line)

        if err != nil {
            fmt.Println("写入文件时出错:", err)
            return
        }
}

    fmt.Println("加密完成") 
}

```
My sealing directory like :
![image](https://user-images.githubusercontent.com/43697225/228210038-3cc29c8c-7f9f-4159-acbb-59f3745739f9.png)

**Comment by Nirusu** [comment]
By default, if you don't define `PWD` as an environment variable in enclave.json, your enclave has `/` as its current working directory. Given that you use relative paths for `os.Open` and `os.Create`, it cannot find any files given that you defined `target` as `/home/jx/sealing`.

You would either have to use absolute paths, or you can set `PWD` to your target path:
```json
  "mounts": [
    {
      "source": "/home/jx/sealing",
      "target": "/home/jx/sealing",
      "type": "hostfs",
      "readOnly": false
    }
  ],
  "env": [
  {
    "name": "PWD",
    "value": "/home/jx/sealing"
  }
],
```
