### ISSUE TITLE
Shared enclave with multiple apps

### ISSUE THREAD

**Issue by notatestuser** [edgelesssys/ego#203]
Hey. I just have a simple question about whether it’s possible to share an enclave between several running apps. They would have separate binaries.

Perhaps by sharing the enclave.json or private.pem?

Many thanks.

**Comment by thomasten** [comment]
Hi, what do you mean by "share an enclave"? Can you give an example scenario?

**Comment by notatestuser** [comment]
Sure @thomasten, something like this.

```
# build and sign 3 binaries
$ ego run ./a
$ ego run ./b
$ ego run ./c
```
where those 3 binaries can share enclave encrypted data.

**Comment by thomasten** [comment]
If the binaries are signed with the same private key and have the same productID, each can decrypt data that was encrypted with the ProductKey by another one. You usually use this mechanism for providing updated versions of the same app and not to create different apps. Not sure if this has security implications. I guess it depends on the use case.

Another option is to establish a shared key between the apps (depends on the use case how to do that) and each app can seal the shared key with its own key. The actual data is then encrypted with the shared key.
