### ISSUE TITLE
panic: invalid security version/panic: invalid product

### ISSUE THREAD

**Issue by Jansper-x** [edgelesssys/ego#210]
Hi, I'm getting some problems when I try remote_attestation. When I run the remote example in the project, I can verify that the securityversion and productID values in the report are 2 and 1234 respectively.
But when I write a new code to use the remote_attestation function, when verifying the report, the security version and productID values in the report are both 1. Why? I'm two examples running on the same platform and have SGX PCCS configured.
Why are the values of securityversion and productID verified in the sample code 2 and 1234 respectively? How can I judge the securityversion and productID values on my platform? Why are the values of securityversion and productID in the report obtained by the server I wrote different from those obtained by the server in the project?
When I use the server which in this project sample：
![image-20230522211036564](https://github.com/edgelesssys/ego/assets/43697225/3822aa1e-ee9d-43ab-8da5-5cbce0dda887)
When I use my own server：
![image-20230522210829775](https://github.com/edgelesssys/ego/assets/43697225/1294a0a2-7c7e-4d68-9e31-6b656ebb7bad)

**Comment by thomasten** [comment]
Hi, you can set these values for your enclave in enclave.json before signing it. Also see the docs on this: https://docs.edgeless.systems/ego/reference/config#basic-settings
