### ISSUE TITLE
does EGo currently supports ubuntu22.04

### ISSUE THREAD

**Issue by onexie** [edgelesssys/ego#212]
Hi,I want to know if  EGo currently supports ubuntu22.04 now.And what potential issues would there be if I used ego on Ubuntu 22.04?

**Comment by thomasten** [comment]
Hi, Ubuntu 22.04 isn't officially supported yet. However, with the EGo snap, you can build and run enclaves. You cannot build remote attestation clients (i.e., apps using the eclient package).
The EGo deb package doesn't work on 22.04.
Alternatively, you can use an ubuntu:20.04 docker container.

**Comment by onexie** [comment]
Thank you,I got it.

**Comment by thomasten** [comment]
@onexie EGo v1.4.0 now supports Ubuntu 22.04
