### ISSUE TITLE
How to ensure the integrity of the code running in the enclave during remote attestation?

### ISSUE THREAD

**Issue by Jansper-x** [edgelesssys/ego#215]
Escuse me, I have a problem while learning this project.
How to ensure the integrity of the code running in the enclave during remote attestation?
For example, the user uses ego to run a program 'sample1' in the enclave, how can he determine from the remote attestation that the program running in the enclave is ''sample1'' without being inserted into some other code fragments. Does ego or remote attestation provide operations such as verifying the hash value of the code? 
In the example of remote_attestation in this project, how does the client confirm that the server code running in ego is the original server?If the server is not honest, he made modifications privately after the client reviewed his own code. I haven't seen the process of passing and verifying code hash in the process of remote attestation. So how can the client detect this change. I don't see anything like that described in the remote_attestation example, so I'm a bit confused.

**Comment by Jansper-x** [comment]
When I was learning sgx, I didn't find relevant detailed descriptions. Where can I get detailed information about remote attestation implementations. Thanks.

**Comment by thomasten** [comment]
Hi, you're right that if you do attestation based on SignerID like in the example, you trust the party that signed the enclave. If you want to ensure the integrity of the code, you would check the UniqueID instead. This is the hash of the code (and enclave configuration).
EGo uses the attestation implementation of Open Enclave. Here's an explanation of the process: https://github.com/openenclave/openenclave/blob/master/samples/attestation/README.md

**Comment by Jansper-x** [comment]
> Hi, you're right that if you do attestation based on SignerID like in the example, you trust the party that signed the enclave. If you want to ensure the integrity of the code, you would check the UniqueID instead. This is the hash of the code (and enclave configuration). EGo uses the attestation implementation of Open Enclave. Here's an explanation of the process: https://github.com/openenclave/openenclave/blob/master/samples/attestation/README.md

How does the client calculate this UniqueID for verification

**Comment by thomasten** [comment]
The client can use the [ego uniqueid](https://docs.edgeless.systems/ego/reference/cli#ego-uniqueid) command for this
