### ISSUE TITLE
about heapSize max limit

### ISSUE THREAD

**Issue by onexie** [edgelesssys/ego#219]
### Issue description
Hi,for some reason our program will use a lot of memory,when I use ego with heapSize config greater than 50240(we are currently configuring the heapsize to 45240,which runs correctly),and use "ego bundle" to package app,if I run the bundle-app ,then will casue the following err:
<img width="1206" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/8b914609-f949-422a-80d3-1efec2bb9375">
here is my enclave.json:
<img width="206" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/6f767bb6-ec95-43e2-9698-b8bb9928aa54">
and here is my test code:
```go
package main

import (
        "fmt"
        "time"

        "github.com/bits-and-blooms/bloom/v3"
)

func main() {
        for {
                bloomFilter := bloom.NewWithEstimates(800000000, 0.000001)
                fmt.Println("Bloom filter created")
                for i := 0; i < 800000; i++ {
                        bloomFilter.Add([]byte(fmt.Sprintf("test%d", i)))
                }
                time.Sleep(60 * time.Second)
        }
}

**Comment by thomasten** [comment]
Hi, `err=0xa` is ENCLAVE_OUT_OF_MEMORY. If the heapSize is near you free RAM size, it may be caused by enclave memory overhead (e.g., alignment requirements).
If you have much more free RAM and still get this error, SGX might not be able to use all of your RAM.

**Comment by onexie** [comment]
> Hi, `err=0xa` is ENCLAVE_OUT_OF_MEMORY. If the heapSize is near you free RAM size, it may be caused by enclave memory overhead (e.g., alignment requirements). If you have much more free RAM and still get this error, SGX might not be able to use all of your RAM.

thank you for reply,my server has 128G memory,if there any other ways to solve it.

**Comment by thomasten** [comment]
Not sure. I couldn't reproduce it with a VM of 64G or 128G memory.
What's the output of `numactl -H`?

**Comment by onexie** [comment]
> Not sure. I couldn't reproduce it with a VM of 64G or 128G memory. What's the output of `numactl -H`?
following image is "numactl -H" output
<img width="284" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/ebe24695-3632-47e8-8ff1-c276c0e46610">

**Comment by onexie** [comment]
> Not sure. I couldn't reproduce it with a VM of 64G or 128G memory. What's the output of `numactl -H`?

following is output of numactl -H:
<img width="247" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/3222a9af-0d42-4d71-b1ab-b29dd8203a65">

**Comment by thomasten** [comment]
What CPU model is this?

**Comment by thomasten** [comment]
According to [1], you can get the maximum enclave size with `cpuid | grep MaxEnclaveSize`. I think it depends on the CPU and maybe on the mainboard and/or BIOS settings. The maximum value for `heapSize` will be smaller than this value.

[1] https://www.intel.com/content/www/us/en/support/articles/000089548/software/intel-security-products.html

**Comment by onexie** [comment]
thank you very much,I got it.
