### ISSUE TITLE
Is ego do different with sgx1.0 and sgx2.0

### ISSUE THREAD

**Issue by onexie** [edgelesssys/ego#226]
Hi,Sgx2.0 supports dynamic memory,so program can use more memory in running.but now  our program build by ego run with sgx2.0 which allocated 80G of memory for heapSize,often encounter the following problems  when the program use about 20G of memory:
<img width="842" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/f8af186b-0c66-4c93-8fd1-b2820e07a50a">

**Comment by thomasten** [comment]
Hi, Enclave Dynamic Memory Management (EDMM) is not supported by Open Enclave (which EGo is based on) yet and I think there's no timeline when it will be implemented. So it is correct that you allocate large memory via heapSize.
The error that you get is not expected. We will investigate and come back to you once we know more.

**Comment by onexie** [comment]
On my test,I found this no matter how I set the heapSize, 20G, 32G, 64G, or 80G, there will always be an exception when the memory exceeds approximately 16G.  Err info:
runtime: memory allocated by OS [0x7f836b800000, 0x7f8417000000) not in usable address space: end outside usable address space
fatal error: memory reservation exceeds address space limit

following is my test code:
```go
package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/bits-and-blooms/bloom/v3"
)

func main() {
	{
		bloomFilterList := []*bloom.BloomFilter{}
		for i := 0; i < 100; i++ {
			bloomFilter := bloom.NewWithEstimates(800000000, 0.000001)
			fmt.Printf("%s: Bloom filter %d created\r\n", time.Now().Format("2006-01-02 15:04:05"), i+1)
			bloomFilterList = append(bloomFilterList, bloomFilter)
			PrintMemUsage()
			time.Sleep(1 * time.Second)
		}
		fmt.Printf("create %d bloom filter done\r\n", len(bloomFilterList))
	}

}

// PrintMemUsage outputs the current, total and OS memory being used. As well as the number
// of garage collection cycles completed.
func PrintMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// For info on each, see: https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("%s,Alloc = %v MiB,TotalAlloc = %v,Sys = %v MiB,NumGC = %v\r\n", time.Now().Format("2006-01-02 15:04:05"), bToMb(m.Alloc), bToMb(m.TotalAlloc), bToMb(m.Sys), m.NumGC)
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}
```

**Comment by onexie** [comment]
Hi,I found some code about memory limits  in  ertgo  :
"src/runtime/malloc.go" 
<img width="942" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/4791a75d-ec63-4330-93d6-15d908725c75">

<img width="974" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/212f603f-5982-4e3f-8791-5498a727401a">


"src/runtime/edgeless_linux_amd64.go "
<img width="659" alt="image" src="https://github.com/edgelesssys/ego/assets/116145646/4fdaed47-48c5-40b9-9d46-c53483dac4a6">

But I don't know how to modify these.

**Comment by thomasten** [comment]
We merged a fix for this to the master branch. You can [build DEB packages of the current master via Docker](https://github.com/edgelesssys/ego#build-via-docker).

**Comment by onexie** [comment]
> We merged a fix for this to the master branch. You can [build DEB packages of the current master via Docker](https://github.com/edgelesssys/ego#build-via-docker).

Thank you
