### ISSUE TITLE
issue with reproducibility

### ISSUE THREAD

**Issue by sharathguvvala** [edgelesssys/ego#232]
I am unable to create reproducible builds, using [https://github.com/edgelesssys/ego/tree/master/samples/helloworld](https://github.com/edgelesssys/ego/tree/master/samples/helloworld) as a reference
I am using ego version 1.4.1
Getting openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
I have added openssl 1.1.1 installation also, are there any changes to the dockerfile given in the example as the given example is for ego v 1.0.0

Also i am not able to run `ego run ABC` in background with nohup, is that in anyway related to ego?

**Comment by thomasten** [comment]
Hi, thanks for reporting. We'll update the sample and fix some issues with it.

Regarding nohup, it works fine for me. Doesn't it run at all or does it stop when the terminal is closed?
Can you provide a minimal example code and the exact commands/steps to reproduce?

**Comment by thomasten** [comment]
We updated the reproducible_build sample. It should fix your issue.
