### ISSUE TITLE
Wasmer Sample -> Wasmtime Sample

### ISSUE THREAD

**Issue by MuffinsThaCat** [edgelesssys/ego#238]
[New Thread 0x7ffff75ff640 (LWP 1748643)]
[erthost] entering enclave ...
[New Thread 0x7ffff6dfe640 (LWP 1748644)]
[New Thread 0x7ffff65fd640 (LWP 1748645)]
[New Thread 0x7ffff5dfc640 (LWP 1748646)]
[New Thread 0x7ffff55fb640 (LWP 1748647)]
[New Thread 0x7ffff4dfa640 (LWP 1748648)]
[New Thread 0x7ffff45f9640 (LWP 1748649)]
[ego] starting application ...
[Thread 0x7ffff45f9640 (LWP 1748649) exited]
[Thread 0x7ffff4dfa640 (LWP 1748648) exited]
[Thread 0x7ffff55fb640 (LWP 1748647) exited]
[Thread 0x7ffff5dfc640 (LWP 1748646) exited]
[Thread 0x7ffff65fd640 (LWP 1748645) exited]
[Thread 0x7ffff75ff640 (LWP 1748643) exited]
[New Thread 0x7ffff45f9640 (LWP 1748650)]
[New Thread 0x7ffff4dfa640 (LWP 1748651)]
[New Thread 0x7ffff55fb640 (LWP 1748652)]
[New Thread 0x7ffff5dfc640 (LWP 1748653)]
[New Thread 0x7ffff75ff640 (LWP 1748654)]
[New Thread 0x7ffff65fd640 (LWP 1748655)]
[New Thread 0x7ffff3df8640 (LWP 1748656)]
[New Thread 0x7ffff35f7640 (LWP 1748657)]
[New Thread 0x7ffff2df6640 (LWP 1748658)]
[New Thread 0x7ffff25f5640 (LWP 1748659)]
[New Thread 0x7fffb1aa5640 (LWP 1748660)]
[New Thread 0x7fffb12a4640 (LWP 1748661)]
[New Thread 0x7fffb0aa3640 (LWP 1748662)]
[New Thread 0x7fff7bfff640 (LWP 1748663)]
[New Thread 0x7fff7b7fe640 (LWP 1748664)]
[New Thread 0x7fff7affd640 (LWP 1748665)]
[New Thread 0x7fff7a7fc640 (LWP 1748666)]

Thread 3 "ego-host" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffd4113000 (LWP 1748644)]
0x00007fffb37930c9 in pthread_atfork ()

### To reproduce

The same steps as /wasmer converted to wasmtime in this repository and branch: https://github.com/rhombus-tech/programs_go/tree/feat/wasmtime/wasmtime-sample

### Expected behavior
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
Results of `sum`: 3

### Additional info
No :/.  Enjoying the project so far! Help is appreciated.

**Comment by MuffinsThaCat** [comment]
Different when I try on AWS:

Setting environment variable "LD_PRELOAD" to null value.
Reading symbols from /opt/ego/bin/ego-host...
(No debugging symbols found in /opt/ego/bin/ego-host)
Starting program: /opt/ego/bin/ego-host /opt/ego/bin/../share/ego-enclave:wasmtime_sample
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[erthost] running in simulation mode
[erthost] loading enclave ...

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) bt
No stack.

**Comment by thomasten** [comment]
It works for me with the following in c.go:
```go
/*
#cgo LDFLAGS: -static-libgcc
int gnu_get_libc_version() { return 0; }
int __register_atfork() { return 0; }
int __res_init() { return -1; }
*/
import "C"
```
and then just `ego-go build` without any env vars. Can you confirm?

**Comment by MuffinsThaCat** [comment]
> It works for me with the following in c.go:
> 
> ```go
> /*
> #cgo LDFLAGS: -static-libgcc
> int gnu_get_libc_version() { return 0; }
> int __register_atfork() { return 0; }
> int __res_init() { return -1; }
> */
> import "C"
> ```
> 
> and then just `ego-go build` without any env vars. Can you confirm?

Confirmed. Much appreciated👍

**Comment by thomasten** [comment]
Great! Please consider contributing your sample to this project (after fixing it and cleaning it up). It may be helpful to others.

**Comment by MuffinsThaCat** [comment]
That's the plan 👍
