### ISSUE TITLE
Help with running a docker image inside SGX using Ego

### ISSUE THREAD

**Issue by polestar1988** [edgelesssys/ego#239]
Dear All, 
I want to run a docker image inside SGX using Ego, But I have no idea where can I start or find a reference which has explained how to run a docker container inside SGX step by step. Could any body help me with this?
Thanks

**Comment by thomasten** [comment]
Hi,
You can't run a docker image inside SGX, but you can run SGX and EGo inside a docker image. That means that if you have a Go application that you want to distribute as a docker image, you can modify the Dockerfile such that the application is built with EGo and the SGX runtime libraries are added.
You can take a look at this sample, which builds a docker image of the helloworld sample: https://github.com/edgelesssys/ego/tree/master/samples/reproducible_build
