### ISSUE TITLE
Remote attestation over TLS format

### ISSUE THREAD

**Issue by tiziano88** [edgelesssys/ego#26]
https://github.com/edgelesssys/ego/blob/3d9a417efb206230a78490fc9773465480c92b9a/samples/remote_attestation/ra_client/client.go#L37-L56

AFAICT, currently the ego library (or at least, the RA example) rely on exposing additional HTTP endpoints on the same server to serve the self-signed cert and a report that binds that to a verifiable SGX quote, and then requires the client to establish a new connection to the server using that (now verified) certificate. This only works if the server is reachable again over a separate connection by the same client (either because there is a single instance of it, or because of some session stickiness, though that would have to be at the TCP level since load balancers would not have any other information).

Have you considered instead to embed the quote in an extension of the same TLS cert that is used for the "real" connection, so that a client may verify that contextually to establishing the connection?

cc @ipetr0v @anghelcovici @dreemkiller

**Comment by dreemkiller** [comment]
For the solution above, how does the client know that it's request to `url+"/report"` has not been intercepted and that the certificate it receives from `url+"/cert"` is tied to that report?

In a typical attestation protocol, the client must generate  a challenge value(large, non-repeating, perhaps random) that it sends to the server to be embedded in the report.

Regarding @tiziano88's suggestion above: There's a similar problem. Without a challenge from the client, the scheme is subject to a replay (or even a MitM) attack.

**Comment by tiziano88** [comment]
> For the solution above, how does the client know that it's request to `url+"/report"` has not been intercepted and that the certificate it receives from `url+"/cert"` is tied to that report?

*I think* it's not necessary for the client to know that. In principle the client may even get `/report` and `/cert` from two separate, both untrusted / plaintext endpoints, possibly at different times and on different hosts, right? The only convincing evidence the client will accept is whether there is a(ny) cert whose hash appears in a valid report. Reports are verified independently by checking against some Intel SGX public key I guess. Or did I miss something else?
 
> In a typical attestation protocol, the client must generate a challenge value(large, non-repeating, perhaps random) that it sends to the server to be embedded in the report.
> 
> Regarding @tiziano88's suggestion above: There's a similar problem. Without a challenge from the client, the scheme is subject to a replay (or even a MitM) attack.

It is correct that an attacker may replay a previous certificate, but is that a real problem in practice? The attacker would still not be able to intercept anything encrypted based on the replayed certificate, will it?

**Comment by tiziano88** [comment]
cc @sethmoo @keithmoyer

**Comment by thomasten** [comment]
Hi @tiziano88 and @dreemkiller,

thanks for the discussion. I understand your perspective regarding the challenge @dreemkiller. However, in the case of TLS connections, I really believe that all we need to know is that the certificate belongs to a "good" enclave with certain properties. I agree with @tiziano88 that the quote could actually come from an untrusted source.

The EGo API currently offers only basic GetReport/VerifyReport functions. The sample demonstrates a simple, yet meaningful way to use them. But I like your suggestion @tiziano88 to embed the quote in the certificate directly for convenience! I believe we discussed this at one point but didn't pursue it - will create a ticket.

**Comment by tiziano88** [comment]
Thanks @thomasten ! In addition to embedding the quote in the cert, it would also be useful to generate a cert that is not quite self-signed, but it is actually signed by a regular CA (and therefore bound to a domain name) in addition to being part of a remote attestation quote. This way the client would know that the server endpoint is not only running in a TEE with the expected configuration, but also on a machine that is owned by a specific organisation (e.g. example.com). I don't have a concrete suggestion on how to actually achieve this in practice though, I hope we can use this (or another) issue as a discussion to come up with something together perhaps.

**Comment by flxflx** [comment]
Hi @tiziano88 ! Yeah, that sounds useful. We have been experimenting with getting Let's Encrypt certificates from within enclaves using the ACME protocol. However, we have so far always used standalone quotes to establish trust. Given your input, we are now thinking along the following lines: 

(1) get quote for the public key, (2) send a CSRs that includes the quote in some field, (3) get back a cert from a CA (eg, Let's Encrypt) that binds CA cert, enclave pubkey and quote.

What do you think?

**Comment by tiziano88** [comment]
Nice idea, I think that would work, but it requires a round trip to the CA in order to get the CSR signed.

I was hoping there is a way, given an already signed cert (and private key) that might have been provisioned in whatever way by a CA for the particular domain in question, to do something about it in order to bind the report on the enclave side (instead of on the CA side).

Chatting with @dreemkiller yesterday, a slightly different option may be to actually just use the CA signed cert (with no extensions), but modify the client so that the report verification is done after the TLS connection with the TEE is established, for example by making an HTTPS request *over that channel* to fetch the report (and if the report validation, that channel would be closed immediately).

The report may cover one of two things at this point:
- (ideal, but perhaps not very easy to implement) the server would get the TLS session key and get that (or its hash) included in the TEE report, and provide that to the client; then the client would know that that particular TLS session does indeed terminate in the TEE that signed that report; I guess this is somewhat similar to [TLS token binding](https://en.wikipedia.org/wiki/Token_Binding), but I have not used that in practice so I'm not sure
- (easier to implement) the server would just generate a TEE report over the hash of the certificate used for that session; I assume that it is possible for the client to retrieve the certificate from the TLS session itself after it is established, but I am not actually sure; this is actually quite similar to EGo's current approach, with the difference that
  * it uses a CA-signed cert instead of a self-signed cert (solving the domain binding problem)
  * it exposes the report from within the already established TLS connection, rather than requiring a reconnection (solving the load balancer / session stickiness problem)

In addition, for any of these possible approaches, it may be nice (although perhaps not essential) for the client to provide a random nonce (e.g. via an HTTP query param), and include that in the TEE report, in order to guarantee freshness and avoid replay attacks, as @dreemkiller mentioned above. I would have to think more to convince myself there is actually a viable attack that relies only on the replay of a report without freshness, but I guess better safe than sorry, and it would not be very hard to implement anyways (apart from the fact that the TEE would have to generate a report for each connection, instead of caching it forever).

**Comment by flxflx** [comment]
I see. Option two makes a lot of sense to me. Getting the cert on the client side is easy. We could probably provide an augmented TLS library that transparently takes care of fetching the quote and verifying the cert against it. I don't think that nonces are required in the TLS setting.

Regarding self-signed certificates and re-connects: we deploy apps using our Marblerun on K8s. The Marblerun Coordinator has a self-signed cert and uses that to issue certs for the individual pods/enclaves. Thus each cluster has one CA with a self-signed cert.

**Comment by tiziano88** [comment]
For the record, it looks like it is also easy enough to get the server cert in a Rust TLS client (which is what we care about most): https://docs.rs/rustls/0.19.0/rustls/trait.Session.html#tymethod.get_peer_certificates @ipetr0v

**Comment by m1ghtym0** [comment]
Lots of great and valid points/ideas have been raised already.
Let me explain a few things on our design and reasoning approach so far:
* We generally differentiate two scenarios with EGo
  * Standalone Applications
  * Microservice architectures running with our service-mesh Marblerun
* For the remote-attestation aspect, so far we've focused mostly on the latter scenario
* Using a CA-signed certificate instead of self-signed makes absolute sense for domain binding
  * Felix already mentioned the ACME-based solutions we experimented on
    * For the standalone scenario, we should provide an interface potentially with a call back that returns a certificate
    * For the microservice scenario, we envision our service-mesh (Marblerun) to take care of this. Note that most CA-signed Certs are strict leaf certificates, hence, in a microservice scenario, we'll probably want one certificate distributed to all instances. We'll think about adding a feature to our secrets distribution for CA-signed certs
* Binding the quote to the TLS session makes perfect sense and fetching the quote over the same session is the logical consequence. We haven't followed that route implementation-wise because we refrained from a dedicated client-lib
  * As Felix said, it should be straightforward to implement such an idea. Providing both a server and client interface in the EGo-Lib
  * Note, that in the service-mesh scenario we've implemented another approach, where each service is authenticated via remote-attestation by the mesh-controller. Each service is then provided with a certificate signed by the mesh-controller. The client only needs to fetch the root certificate ONCE for the whole cluster via a remote attestation step. Of course, in the standalone scenario, this would not apply.
