### ISSUE TITLE
Unable to sign compiled executable 

### ISSUE THREAD

**Issue by harshu4** [edgelesssys/ego#260]
### Issue description

I am not able to sign my compiled binary. I am able to build and sign binary of the samples provided but when i try to compile and sign my own code it gives the following error 

EGo v1.5.0 (952087dd77320d37883d446c97bb21317163e0dc)
ERROR: The .oeinfo section is missing in the binary.
Maybe the binary was not built with 'ego-go build'?

### To reproduce

1.  git clone https://github.com/harshu4/openmesh-node
2. cd openmesh-node
3. ego-go build /cmd/app/main.go
4. ego sign 

### Expected behavior
Expected behaviour would be that the binary is signed properly

**Comment by harshu4** [comment]
used to work with older version of ego

**Comment by thomasten** [comment]
fixed in v1.5.2
