### ISSUE TITLE
Will terminate when in ego enclave, but work fine when not in.

### ISSUE THREAD

**Issue by vincentiss** [edgelesssys/ego#263]
Dear you.
My go project works fine normal, but  it will exit after running for a while in ego, sometimes an hour, sometimes a few hours. 
And I cann't see any log such as some crash errors, just ```Terminated```
Are there any restrictions when running? For example, memory or queue?
I try to change heap size from 512 to 8192, but still not work.
Could you give me some help or suggestion? Thank you.

**Comment by thomasten** [comment]
Hi,
There are no known restrictions. We have EGo apps running for months without interruption.

Let's check the following things:
* Do you think your app runs longer when setting heap size to 8192? (may be hard to tell)
* Will it terminate earlier when putting high load on it? Can you try to maximize the load and check?
* What's the exit code? (You can check with `echo $?` right after it terminated.) Is it always the same?
* Is this a debug enclave (`"debug": true` in enclave.json)? If not, can you enable debug and check if it prints a longer error message on exit?
* Does the app also exit when running in simulation mode?

**Comment by vincentiss** [comment]
Thank you first. I've been testing for the past two days.


* Do you think your app runs longer when setting heap size to 8192? (may be hard to tell)
    Exactly no.
 
* Will it terminate earlier when putting high load on it? Can you try to maximize the load and check?
     I tried,  no issues found.

* What's the exit code? (You can check with echo $? right after it terminated.) Is it always the same?
    Yes, always got 143.

* Is this a debug enclave ("debug": true in enclave.json)? If not, can you enable debug and check if it prints a longer error * message on exit?
     It has always been in debug mode. 

* Does the app also exit when running in simulation mode?
    Also exits in simulation mode.

**Comment by thomasten** [comment]
Okay. Let's see if we can find out more with gdb. Please run
```
OE_SIMULATION=1 ego-gdb -ex=r --args ./your-app
```
until a signal is received.

If it's SIGTERM, get the pid of the process that sent this signal with
`print $_siginfo._sifields._kill`
and then check your running processes for this pid.

gdb may also receive another signal first. In that case, inspect that stack trace with `bt`.

**Comment by vincentiss** [comment]
Oh, I found the issue.

1. login server by ```ssh```.
2. run ```tmux``` or ```nohup``` to run ego run myapp.
3. close ```ssh``` connection.
4. Then receive ```Exception <class 'KeyboardInterrupt'>``` 

The interesting thing  is everything work  fine if I did not run app in ego.
So could you give me more suggestion? Thank you very much.

**Comment by thomasten** [comment]
I can't reproduce with `nohup`. Can you provide a minimal example code and the exact commands to reproduce?

**Comment by vincentiss** [comment]
I will guess that is my environment problem if you still can't reproduce it.

This is my testing code. 
```
package main

import (
        "fmt"
        "github.com/gin-gonic/gin"
)

func main() {
        fmt.Println("--main--")

        r := gin.Default()
        r.GET("ping", func(ctx *gin.Context) {
            ctx.JSON(200, gin.H{
                "message": "pong",
            })
        })
        r.Run(":8080")

        fmt.Print("end")
}
```

**Comment by vincentiss** [comment]
Ok .. It's fine now after changed another server.
Anyway thank you.
