### ISSUE TITLE
Error Running Wasm Inside Ego-Runtime 

### ISSUE THREAD

**Issue by harshu4** [edgelesssys/ego#264]
### Issue description

When trying to execute wasm with memory allocation 

Error : panic: Failed to instantiate the module: Insufficient resources: Failed to create memory: Error when allocating memory: Out of memory (os error 12)

### To reproduce

1. In the go-wasmer example replace the wasm-bytes with 
```
(module
  (type (;0;) (func (param i32 i32) (result i32)))
  (func (;0;) (type 0) (param i32 i32) (result i32)
    local.get 0
    local.get 1
    i32.add)
  (memory (;0;) 16)
  (global (;0;) i32 (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "sum" (func 0))
  (export "__data_end" (global 0))
  (export "__heap_base" (global 1)))

```
2. use 
```
CGO_CFLAGS="-I$PWD/wasmer/include" CGO_LDFLAGS="$PWD/wasmer/lib/libwasmer.a -ldl -lm -static-libgcc" ego-go build -tags custom_wasmer_runtime
``` 

to build 

3. use 
``` ego sign ```

4. use 
``` ego run ```

Is their anyway to support this memory allocation ?

**Comment by thomasten** [comment]
Hi,
wasmer reserves 6 GiB of address space for allocations. When running in the enclave, this needs to be preallocated. You can set `heapSize` in `enclave.json` to, e.g., `7168`.

**Comment by harshu4** [comment]
That worked, Thanks!
