### ISSUE TITLE
version `OPENSSL_1_1_1k' not found (required by openssl)

### ISSUE THREAD

**Issue by yanminmin** [edgelesssys/ego#265]
# /var/lib/snapd/snap/bin/ego-dev.ego-go sign helloworld
go sign: unknown command
Run 'go help' for usage.
[root@iZj6chrf5i84ow133gvyl2Z helloworld]# /var/lib/snapd/snap/bin/ego-dev.ego  sign helloworld
EGo v1.5.0 (952087dd77320d37883d446c97bb21317163e0dc)
Generating new private.pem
openssl: /snap/ego-dev/26/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1k' not found (required by openssl)

panic: exit status 1

goroutine 1 [running]:
ego/cli.(*Cli).createDefaultKeypair(0xc000022ff0, {0xc000012bf0, 0xb})
	ego/cli/sign.go:192 +0x445
ego/cli.(*Cli).signWithJSON(0xc000022ff0, 0xc0000d4000)
	ego/cli/sign.go:99 +0x6da
ego/cli.(*Cli).signExecutable(0xc000022ff0, {0x7ffd424af403, 0xa})
	ego/cli/sign.go:121 +0xd3
ego/cli.(*Cli).Sign(0x0?, {0x7ffd424af403?, 0x0?})
	ego/cli/sign.go:221 +0xda
ego/ego/cmd.NewRootCmd.newSignCmd.func2(0xc0000bd000?, {0xc000038260?, 0x4?, 0x80cbe7?})
	ego/ego/cmd/sign.go:35 +0x45
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0xc000038230, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
ego/ego/cmd.Execute()
	ego/ego/cmd/root.go:13 +0x1f
main.main()
	ego/ego/main.go:24 +0x98

**Comment by thomasten** [comment]
1. Please use `ego sign` instead of the full path or not existing `go sign`
2. What OS do you use?
3. As a workaround, try generating the key with `openssl genrsa -out private.pem -3 3072` and then run `ego sign` again

**Comment by yanminmin** [comment]
1.yes,I use `ego sign`
2.centos 8 
3.I have tried generating the key with openssl genrsa -out private.pem -3 3072 and then success.
thanks.
