### ISSUE TITLE
 Is this code about `erthost`  open source?

### ISSUE THREAD

**Issue by yanminmin** [edgelesssys/ego#266]
I wanted to know the rationale behind this `ego run`.But I couldn't find the bottom layer,and I found`erthost` to execute the relevant commands.
So what is erthost? Is this open source? Is this code about `erthost`  open source?

**Comment by thomasten** [comment]
erthost is part of Edgeless RT, which EGo is based on: https://github.com/edgelesssys/edgelessrt/tree/master/src/tools/erthost
