### ISSUE TITLE
Cannot use ego sign when installing from deb package in Ubuntu 22.04 without OpenSSL 1.1

### ISSUE THREAD

**Issue by whyamiroot** [edgelesssys/ego#270]
### Issue description

On Ubuntu 22.04, e.g. ubuntu:jammy-20240405 image, `ego sign` fails with a missing libcrypto library:

```
EGo v1.5.0 (952087dd77320d37883d446c97bb21317163e0dc)
Generating new private.pem
ERROR: /opt/ego/bin/ego-oesign: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

```bash
$ apt list --installed | grep ssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libssl-dev/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.15 amd64 [installed]
libssl3/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.15 amd64 [installed]
openssl/jammy-updates,jammy-security,now 3.0.2-0ubuntu1.15 amd64 [installed,automatic]
```

Ubuntu 22.04 doesn't have OpenSSL 1.1 anymore, and installing it without replacing the system's OpenSSL 3 proved to be difficult for me.

On some of the servers where I tried it, libcrypto 1.1 was *seemingly* installed with core20 snap, then `ego sign` command worked. I'd rather not use snap, though, if possible.

### To reproduce

1. On a fresh Ubuntu 22.04 install ego dependencies and ego using the deb package from the Releases page
2. Clone this repo, check out one of the samples, build with ego-go, try to sign with `ego sign`

### Additional info
OpenEnclave allows linking with OpenSSL 3.1 since 0.19.2, perhaps we could have deb packages for Ubuntu 22.04 linked with that? Or perhaps ship deb packages for Ubuntu 22.04 with libssl-dev 1.1 included.

**Comment by thomasten** [comment]
Hi, there actually is a deb package for 22.04 on the releases page.

**Comment by whyamiroot** [comment]
Ah, so what happened was I was testing an installation script, where I forgot to change 20.04 to 22.04, and the script wasn't working. Then I was double checking it by executing the build steps from the README manually, there I was actually downloading the one for 22.04, and I blamed snap's core20 package for the difference :facepalm:

There's no issue here actually, I changed my script and it' all good now, thank you.
