### ISSUE TITLE
Consider moving away from deprecated square/go-jose.v2 package to go-jose/go-jose

### ISSUE THREAD

**Issue by whyamiroot** [edgelesssys/ego#277]
square/go-jose is deprecated, and contains at least one vulnerability, though I'm not sure if it's relevant for EGo

https://github.com/advisories/GHSA-c5q2-7r4c-mv6g

**Comment by thomasten** [comment]
Thanks for notifying! The Go package at v1.5.3 uses github.com/go-jose/go-jose/v4
