### ISSUE TITLE
ego-go build failed--ego version low?

### ISSUE THREAD

**Issue by asdfslw** [edgelesssys/ego#289]
// ego-go build  xx/main.go
ertgo: warning: module xxx requires go >= 1.22.2 (running go 1.21.11; GOTOOLCHAIN=local)
go: updates to go.mod needed; to update it:
	go mod tidy
// ego-go mod tidy
ertgo: warning: module xxx requires go >= 1.22.2 (running go 1.21.11; GOTOOLCHAIN=local)
go: updating go.mod requires go >= 1.22.2 (running go 1.21.11; GOTOOLCHAIN=local)

ego version = v1.6.0
ego-go version = 1.21.11
os = Ubuntu 22.04.4 LTS

If I can't remove the dependency on module xxx, how can I fix the problem ?

**Comment by thomasten** [comment]
Hi, please run `go mod tidy` with the default `go` compiler. Then run `ego-go build` again. It will still print warnings, but these can often be ignored.

**Comment by asdfslw** [comment]
> Hi, please run `go mod tidy` with the default `go` compiler. Then run `ego-go build` again. It will still print warnings, but these can often be ignored.

As I currently understand it, ego can be compiled and run without additional go.
According to you, I need to install a higher version of go to help solve this problem?

**Comment by thomasten** [comment]
Yes, if your dependencies require 1.21.11 or less, you don't need additional go.
ego-go can often build modules that define a later version, but it cannot tidy them.
