### ISSUE TITLE
testing.(*T).TempDir() panics in cleanup

### ISSUE THREAD

**Issue by RmbRT** [edgelesssys/ego#291]
### Issue description
In tests, calling `t.TempDir()` leads to an error during cleanup:
```
testing.go:1225: TempDir RemoveAll cleanup: unlinkat /tmp/TestExample406597298: bad file descriptor
```
In `enclave.json`, `/tmp` has been mounted as `memfs`. I also had tried using hostfs and mounting the native tmp directory, and also tried mounting the root directory as hostfs.

It worked when I used `tmp, _ := os.MkdirTemp("", "*")` instead, maybe that is an acceptable fix? Although once I added a `defer os.RemoveAll(tmp)`, it also returned an error (not a panic, though). I didn't want to investigate any further, but it seems to be either a problem in `os.Remove/All` in general, or with temp directories in the ego file system. A superficial fix for `t.TempDir()` would be to simply not insist on success of the cleanup operation in the `testing.go` vendor file.

### To reproduce

1. Create a test.
2. Insert `_ = t.TempDir()`
3. `ego-go test -c && ego sign *.test && ego run *.test` (adjust the enclave.json as necessary, obviously)

### Expected behavior
I would have expected this to not panic.

### Additional info
I am using OE_SIMULATION=1, although that should not affect anything IMO. I'm on Ubuntu 24.

**Comment by thomasten** [comment]
Thanks for reporting! We can reproduce this and will investigate.

**Comment by thomasten** [comment]
This is fixed in master and will be included in the next release.

**Comment by RmbRT** [comment]
thanks a lot. Do I close this issue or do you do this?
