### ISSUE TITLE
ego run hangs on entering enclave

### ISSUE THREAD

**Issue by hansinator** [edgelesssys/ego#31]
Hi,

I've been following the steps in readme.md to run a simple hello world example in an enclave using ego run and it hangs forever after printing this:

$ ego run hello
[erthost] loading enclave ...
[erthost] entering enclave ...

However, I am not sure what to expect though. Could you maybe add the output of a successfully running example somewhere to your  build and run instructions?

**Comment by thomasten** [comment]
Hi @hansinator,

Thanks for reporting! I also discovered this bug today and a fix is on the way (https://github.com/edgelesssys/edgelessrt/pull/24).

However, on my machine this happens rarely. Can you try multiple times and see if it works sometimes?

I think it's a good idea to add the output to the README anyway - will do.

**Comment by thomasten** [comment]
added expected output to the helloworld sample's README: https://github.com/edgelesssys/ego/tree/master/samples/helloworld

**Comment by hansinator** [comment]
thank you @thomasten

After trying "ego run" a couple of times it finally just ran as you suggested. I'm looking forward to your fix :)

**Comment by hansinator** [comment]
looks like the problem is solved, at least on my machine

**Comment by thomasten** [comment]
Thanks for replying, just wanted to ask you to test :)
