### ISSUE TITLE
Hashi-corp Vault demo is not running in dev mode and exiting.

### ISSUE THREAD

**Issue by mahiuddinalkamal** [edgelesssys/ego#32]
The below error is generated when running the command: ego run vault server -dev

_**Error initializing Dev mode: error expanding config path "": exec not supported**_

And the vault closes. Please look into it.

**Comment by foobar-glitch** [comment]
I also have this issue

**Comment by thomasten** [comment]
Thanks for reporting! I can reproduce the issue. We will look into it.

**Comment by asamiHamed** [comment]
Is this issue maybe caused by the latest vault version? Which version of vault did you first try with ego?

**Comment by foobar-glitch** [comment]
Is this issue maybe caused by the latest vault version? What version of vault did you test with ego?

**Comment by thomasten** [comment]
I updated the sample's README. Can you try again?
Just tested with the latest master of vault.

**Comment by foobar-glitch** [comment]
It's working with the new command

**Comment by mahiuddinalkamal** [comment]
The issue is resolved now. Thank you.
