### ISSUE TITLE
Support for library enclave

### ISSUE THREAD

**Issue by ibalajiarun** [edgelesssys/ego#41]
Typically, enclaves are built as trusted libraries that are then loaded by the untrusted application during runtime. Does ego support such interfacing? It appears that the current version can only run an trusted application binary on the enclave directly. I understand that one can use sockets to establish a connection between applications, but it comes with some security concerns. 

Awesome project! Thank you!

**Comment by thomasten** [comment]
Yes, with the current version of EGo you cannot partition your app. You could do this with https://github.com/edgelesssys/edgelessrt, but it is not straightforward. ERT is based on Open Enclave, so you would first create a project similar to one targeting OE. You'd compile the Go code to a static library and link it to the enclave. For ecalls/ocalls you'd use EDL and thus need some glue code written in C.

**Comment by ibalajiarun** [comment]
Interesting. Thanks!

**Comment by fxfactorial** [comment]
@thomasten is there an example of this already done?

**Comment by thomasten** [comment]
@fxfactorial I'll try to add one until next week.

**Comment by flxflx** [comment]
So EGo's philosophy is to put entire (micro) services into enclaves. Maybe you can achieve your goals by splitting your app into two services, e.g., a web frontend (A, not inside enclave) and a bitcoin wallet (B, inside enclave). B would then expose a REST or gRPC interface to A. 

The alternative approach is to keep A+B=C as a monolothic service and have a service-internal interface between A and B. This is what folks have been doing historically with SGX and EDL. In my experience, the monolithic approach often makes things more complicated.

@ibalajiarun and @fxfactorial: could you sketch what you are planning to do?
@ibalajiarun: what is your security concern? In most cases it shouldn't make a difference if A and B are communicating through RPC or local procedure calls.

**Comment by ibalajiarun** [comment]
@flxflx I am not very knowledgeable on this topic. I work on consensus protocols, and I use the SGX as a mechanism to provide trust. To provide the trust, the assumption is that the SGX hosts as small amount of code as possible. Effectively, one should be able to verify formally the code running within the enclave. Using the local procedure calls helps us make certain assumptions that we are not able to make with gRPC because the dependencies and resulting size of the code that we should formally verify is large. 

Moreover, with the gRPC approach, I have questions such as how to ensure a one-to-one mapping between the app and the enclave service? My assumption is if the app spawns the service internally, it effectively controls it. With the gRPC approach, there needs to be a mechanism that validates that there is a one-to-one mapping.

**Comment by flxflx** [comment]
I agree, the EGo approach is not well suited for scenarios involving formal verification. (Are there tools for formal verification of Go code?)

Our view is that everything that happens outside the enclave is untrustworthy. Thus, from a security perspective, I'd argue that there is no real difference between the gRPC approach (e.g., via localhost) and the internal approach. However, I agree that each approach has certain advantages wrt to practicality.

**Comment by ibalajiarun** [comment]
I am aware of any Go specific formal verification tools. Certain Binary analysis techniques exist that can help verify binaries in a language-agnostic manner. These techniques work well when the size of the binary is small.

**Comment by thomasten** [comment]
We added a description of the [EGo programming model](https://docs.edgeless.systems/ego/#/knowledge/model) to the docs.
