### ISSUE TITLE
ego run remote-attestation error with own machine which enable SGX-FLC

### ISSUE THREAD

**Issue by ZzTea** [edgelesssys/ego#55]
I'v installed ego using release binary and run samples. helloworld sample is ok, but error occur when I run remote-attestation.
The error details as follows:
![image](https://user-images.githubusercontent.com/8436914/117523977-cd375e80-afed-11eb-9861-bc002528511b.png)
Through the investigation, I felt that there was a problem with parsing the pck certificate in the report, so I printed out the report. I found that the report may be missing a newline character.
![image](https://user-images.githubusercontent.com/8436914/117524056-623a5780-afee-11eb-83c8-82f8f265125f.png)
Please help to confirm whether the above error is caused by this reason. Thanks.

**Comment by thomasten** [comment]
Hi @ZzTea,

according to the error message, it's not the pck certificate itself, but the CRL for the certificate which cannot be parsed. The CRL is obtained via the DCAP Quote Provider Library (QPL, libdcap_quoteprov.so).

Have you successfully performed DCAP attestation with any other SGX SDK on this machine?

EGo is based on Open Enclave and uses its DCAP implementation. Open Enclave has instructions on how to set up the QPL and a PCCS: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md#3-set-up-intel-dcap-quote-provider-library-qpl

This is quite tedious. We are planning to provide something simpler in future.

**Comment by ZzTea** [comment]
@thomasten Thanks reply！I studied the above documents you gave and found that it may be caused by the version of the DCAP related service library. The example in the document shows that the corresponding certificate and other services are v2 version, while my local is v3 version. I will first study the related documents of OE. If there is any question, I will ask for advice. I will close this question first. Thank you very much.

**Comment by thomasten** [comment]
@ZzTea You may also try the ghcr.io/edgelesssys/ego-dev Docker image, run with `--device /dev/sgx`. It should have a working configuration.
