### ISSUE TITLE
ego failed to execute os.Lstat 

### ISSUE THREAD

**Issue by henrychou0620** [edgelesssys/ego#67]
### Issue Description
ego failed d to execute os.Lstat function, whatever directory or file

### Expected behavior  
No error occurs

### Actual behavior 

![image](https://user-images.githubusercontent.com/17446330/121649235-f48cba00-caca-11eb-9911-27bb2d1705e0.png)

### Steps to reproduce this behavior

func main() {
	fi, err := os.Lstat("/etc/")
	fmt.Printf("file info: %v\n", fi)
	if err != nil {
		fmt.Println(err)
	}
}

ego-go build -o main
ego sign main
ego run main

### Additional info / screenshot
- Any additional information or context

**Comment by henrychou0620** [comment]
> Thanks for reporting! We will fix this with the next EGo release.

**Comment by henrychou0620** [comment]
``
I really appreciate your great work, thank you！
> Thanks for reporting! We will fix this with the next EGo release.

**Comment by henrychou0620** [comment]
``
I really appreciate your great work, thank you！
> Thanks for reporting! We will fix this with the next EGo release.

**Comment by thomasten** [comment]
@henrychou0620 This is now fixed in EGo 0.3

**Comment by henrychou0620** [comment]
> @henrychou0620 This is now fixed in EGo 0.3

It works！Thanks for your work！^-^
