### ISSUE TITLE
Pre-loading enclave with files

### ISSUE THREAD

**Issue by ADL-work** [edgelesssys/ego#87]
Hi,

I am trying to run EGo while connecting to EDB via certificate by using go-sql-driver.

In the go codes, it is required to load the ca-cert, user pem key & private key. The go codes work well, but when I tried to build, sign and run with EGo, I had an error mentioning:

> open ./edb.pem: no such file or directory
> panic: open ./edb.pem: no such file or directory

How can I add/preload files, pre-populated data in the enclave?

Thank you for the help,

Regards,

**Comment by thomasten** [comment]
Hi @ADL-work,
We are currently working on the feature of adding files to the enclave image that will then be available through the in-enclave-memory filesystem. Until then you can
* Hardcode the contents of the pem file as string and create a tls.Config for the sql driver similar to https://github.com/edgelesssys/edgelessdb/blob/5d09b993f3ce851a88f58b35b915da0f81d08488/edb/integration_test.go#L874-L893
* Use https://pkg.go.dev/embed
* or (for testing purposes) [mount a directory of the host filesystem](https://docs.edgeless.systems/ego/#/reference/config?id=mounts).

**Comment by ADL-work** [comment]
Hi @thomasten ,

Thank you for the suggestion, I will give it a try and let you know, probably I will try with preloading the pem file as a string first as it seems to be the quick test the capacity :)

Regards,
