### ISSUE TITLE
ego built program does not scale well on multi-cores server

### ISSUE THREAD

**Issue by Glenrun** [edgelesssys/ego#95]
### Issue description

Build a program with ego,  run and bind it to 28 CPU cores. It does not scale well on multi-core, only scale to 3 cores with only 50%-60% CPU usage of each, and other cores are idle. Build with native go, it scales well to all 28 cores, the each CPU load is almost the same. Client requests are enough and same for both two scenarios.

### To reproduce

1. Composed a go program, acting as a http server, mainly use golang crypto package, like ecdsa, elliptic, x509 etc, exposing an interface which generates ecdsa keys and some encoding/decoding.
2. use ego build/sign the program: http-server
3. boot command: `numactl -C 0-27 ego run http-server`
4. use testing tool: `ab` to give enough requests

### Expected behavior

The ego program http-server should scale to 28 cores

### Additional info / screenshot

![image](https://user-images.githubusercontent.com/10444152/142155734-3f5aa8f2-96d8-45bc-b306-b1d591d1290b.png)

**Comment by thomasten** [comment]
Hi @Glenrun,
Thanks for reporting! Can you try setting GOMAXPROCS via enclave.json, e.g.,
```json
    "env": [
        {
            "name": "GOMAXPROCS",
            "value": "20"
        }
    ],
```

**Comment by Glenrun** [comment]
It seems it works, but I didn't set GOMAXPROCS for native go built binary either, why native binary scale automatically?

**Comment by thomasten** [comment]
This is likely a bug. We'll investigate further and try to bring a fix with the next release.

**Comment by Glenrun** [comment]
@thomasten I did another test, gave enough request to the server, it reports a error below, then coredump:
`ERROR: :OE_OUT_OF_THREADS [openenclave-src/host/sgx/calls.c:oe_ecall:615]`

**Comment by thomasten** [comment]
Thanks. This is probably related. Until we've fixed this you may lower the number of GOMAXPROCS until it doesn't run out of threads.

**Comment by thomasten** [comment]
This is fixed now and the fix will be included in the next EGo release.

**Comment by thomasten** [comment]
@Glenrun The release is out and includes the fix.

**Comment by Glenrun** [comment]
@thomasten Thanks, will have a try later

**Comment by thomasten** [comment]
We consider this to be fixed. Feel free to reopen if there are still problems.
