### ISSUE TITLE
Need AAD (additional authentication data) in the SealWith... functions for AES-GCM

### ISSUE THREAD

**Issue by weijiguo** [edgelesssys/ego#97]
### Use case
Currently the SealWith... functions encrypt the supplied plaintext in AES-GCM mode without optionally taking in AAD, which is useful in some cases, for example, ensuring that certain cipher text is encrypted for certain party or use. Enabling AAD prevents attackers from replacing the cipher text with yet another otherwise valid cipher (encrypted with the same key but not for this use or this person, etc.)

### Describe your solution
The option to supply AAD during sealing.

### Additional context
Open Enclave has this: https://github.com/openenclave/openenclave/blob/master/enclave/core/seal.c
The function signature:

oe_result_t oe_seal(
          const oe_uuid_t* plugin_id,
          const oe_seal_setting_t* settings,
          size_t settings_count,
          const uint8_t* plaintext,
          size_t plaintext_size,
          const uint8_t* **additional_data**,
          size_t additional_data_size,
          uint8_t** blob,
          size_t* blob_size)

**Comment by thomasten** [comment]
Thanks for the suggestion, we'll add this.

**Comment by thomasten** [comment]
v0.4.0 of the package now accepts AAD
